import "server-only";

import type { NotificationWorkflow } from "@/data/notificationOperationModel";

export const notificationWorkflowExtensions: NotificationWorkflow[] = [
  {
    id: "ticket-created",
    eventType: "TICKET_CREATED",
    label: "Chamado criado",
    category: "support",
    description: "Avisa criacao de chamado de suporte ou melhoria.",
    criticality: "normal",
    mandatory: false,
    defaultChannels: ["in_app", "brain"],
    audienceScopes: ["company", "role", "user"],
    recipientRules: ["Criador", "Responsavel", "Suporte tecnico", "Lider quando aplicavel"],
    preferenceRules: ["Empresa pode configurar canal", "Usuario pode silenciar nao critico"],
  },
  {
    id: "ticket-updated",
    eventType: "TICKET_STATUS_CHANGED",
    label: "Chamado atualizado",
    category: "support",
    description: "Avisa mudanca de status, atribuicao ou reacao em chamado.",
    criticality: "normal",
    mandatory: false,
    defaultChannels: ["in_app", "brain"],
    audienceScopes: ["company", "role", "user"],
    recipientRules: ["Criador", "Responsavel", "Participantes", "Suporte tecnico"],
    preferenceRules: ["Pode ser suprimido por empresa/perfil/usuario", "Brain mantem contexto"],
  },
  {
    id: "ticket-comment",
    eventType: "TICKET_COMMENT_ADDED",
    label: "Comentario em chamado",
    category: "support",
    description: "Avisa novo comentario em chamado acompanhado pelo usuario.",
    criticality: "normal",
    mandatory: false,
    defaultChannels: ["in_app", "chat", "brain"],
    audienceScopes: ["company", "role", "user"],
    recipientRules: ["Criador", "Responsavel", "Usuarios mencionados", "Participantes"],
    preferenceRules: ["Pode desativar chat", "Pode desativar email", "Evento permanece auditado"],
  },
  {
    id: "doc-published",
    eventType: "DOC_PUBLISHED",
    label: "Documento publicado",
    category: "project",
    description: "Avisa publicacao de documento, wiki ou material de suporte.",
    criticality: "low",
    mandatory: false,
    defaultChannels: ["in_app", "brain"],
    audienceScopes: ["company", "project", "role", "user"],
    recipientRules: ["Usuarios com acesso", "Lideres", "Empresa vinculada"],
    preferenceRules: ["Pode ser desativado por empresa", "Usuario pode silenciar docs", "Brain mantem contexto documental"],
  },
  {
    id: "access-request-created",
    eventType: "ACCESS_REQUEST_CREATED",
    label: "Solicitacao de acesso criada",
    category: "access",
    description: "Avisa nova solicitacao de acesso aguardando revisao.",
    criticality: "high",
    mandatory: false,
    defaultChannels: ["in_app", "email", "brain"],
    audienceScopes: ["role", "global", "user"],
    recipientRules: ["Fila de revisao", "Admin/Global conforme regra", "Solicitante quando aplicavel"],
    preferenceRules: ["Admin pode configurar canal nao critico", "Brain mantem auditoria da fila"],
  },
  {
    id: "access-request-updated",
    eventType: "ACCESS_REQUEST_COMMENT",
    label: "Solicitacao de acesso atualizada",
    category: "access",
    description: "Avisa comentario ou pedido de ajuste em solicitacao de acesso.",
    criticality: "high",
    mandatory: false,
    defaultChannels: ["in_app", "email", "brain"],
    audienceScopes: ["role", "global", "user"],
    recipientRules: ["Solicitante", "Revisor", "Fila de revisao"],
    preferenceRules: ["Pode configurar canais nao criticos", "Evento permanece auditavel"],
  },
  {
    id: "access-request-decision",
    eventType: "ACCESS_REQUEST_ACCEPTED",
    label: "Decisao de acesso",
    category: "access",
    description: "Avisa aprovacao ou rejeicao de solicitacao de acesso.",
    criticality: "critical",
    mandatory: true,
    defaultChannels: ["in_app", "email", "brain"],
    audienceScopes: ["role", "global", "user"],
    recipientRules: ["Solicitante", "Revisor", "Admin responsavel"],
    preferenceRules: ["Nao pode ser desativado", "Auditoria obrigatoria", "Brain recebe contexto"],
  },
  {
    id: "profile-deletion-request",
    eventType: "PROFILE_DELETION_REQUEST",
    label: "Solicitacao de remocao de perfil",
    category: "security",
    description: "Avisa solicitacao sensivel de remocao de perfil e encaminha para revisao.",
    criticality: "critical",
    mandatory: true,
    defaultChannels: ["in_app", "email", "brain"],
    audienceScopes: ["user", "role", "global"],
    recipientRules: ["Usuario solicitante", "Fila de revisao", "Admin/Global"],
    preferenceRules: ["Nao pode ser desativada", "Auditoria obrigatoria", "Brain recebe contexto"],
  },
  {
    id: "profile-deletion-decision",
    eventType: "PROFILE_DELETION_APPROVED",
    label: "Decisao de remocao de perfil",
    category: "security",
    description: "Avisa aprovacao ou rejeicao de remocao de perfil.",
    criticality: "critical",
    mandatory: true,
    defaultChannels: ["in_app", "email", "brain"],
    audienceScopes: ["user", "role", "global"],
    recipientRules: ["Usuario afetado", "Revisor", "Admin/Global"],
    preferenceRules: ["Nao pode ser desativada", "Auditoria obrigatoria", "Brain recebe contexto"],
  },
];

