
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TestRun` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TestRun
 * 
 */
export type TestRunModel = runtime.Types.Result.DefaultSelection<Prisma.$TestRunPayload>

export type AggregateTestRun = {
  _count: TestRunCountAggregateOutputType | null
  _min: TestRunMinAggregateOutputType | null
  _max: TestRunMaxAggregateOutputType | null
}

export type TestRunMinAggregateOutputType = {
  id: string | null
  status: string | null
  created_at: Date | null
}

export type TestRunMaxAggregateOutputType = {
  id: string | null
  status: string | null
  created_at: Date | null
}

export type TestRunCountAggregateOutputType = {
  id: number
  status: number
  created_at: number
  _all: number
}


export type TestRunMinAggregateInputType = {
  id?: true
  status?: true
  created_at?: true
}

export type TestRunMaxAggregateInputType = {
  id?: true
  status?: true
  created_at?: true
}

export type TestRunCountAggregateInputType = {
  id?: true
  status?: true
  created_at?: true
  _all?: true
}

export type TestRunAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TestRun to aggregate.
   */
  where?: Prisma.TestRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TestRuns to fetch.
   */
  orderBy?: Prisma.TestRunOrderByWithRelationInput | Prisma.TestRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TestRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TestRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TestRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TestRuns
  **/
  _count?: true | TestRunCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TestRunMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TestRunMaxAggregateInputType
}

export type GetTestRunAggregateType<T extends TestRunAggregateArgs> = {
      [P in keyof T & keyof AggregateTestRun]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTestRun[P]>
    : Prisma.GetScalarType<T[P], AggregateTestRun[P]>
}




export type TestRunGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TestRunWhereInput
  orderBy?: Prisma.TestRunOrderByWithAggregationInput | Prisma.TestRunOrderByWithAggregationInput[]
  by: Prisma.TestRunScalarFieldEnum[] | Prisma.TestRunScalarFieldEnum
  having?: Prisma.TestRunScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TestRunCountAggregateInputType | true
  _min?: TestRunMinAggregateInputType
  _max?: TestRunMaxAggregateInputType
}

export type TestRunGroupByOutputType = {
  id: string
  status: string
  created_at: Date
  _count: TestRunCountAggregateOutputType | null
  _min: TestRunMinAggregateOutputType | null
  _max: TestRunMaxAggregateOutputType | null
}

type GetTestRunGroupByPayload<T extends TestRunGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TestRunGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TestRunGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TestRunGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TestRunGroupByOutputType[P]>
      }
    >
  >



export type TestRunWhereInput = {
  AND?: Prisma.TestRunWhereInput | Prisma.TestRunWhereInput[]
  OR?: Prisma.TestRunWhereInput[]
  NOT?: Prisma.TestRunWhereInput | Prisma.TestRunWhereInput[]
  id?: Prisma.StringFilter<"TestRun"> | string
  status?: Prisma.StringFilter<"TestRun"> | string
  created_at?: Prisma.DateTimeFilter<"TestRun"> | Date | string
}

export type TestRunOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type TestRunWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TestRunWhereInput | Prisma.TestRunWhereInput[]
  OR?: Prisma.TestRunWhereInput[]
  NOT?: Prisma.TestRunWhereInput | Prisma.TestRunWhereInput[]
  status?: Prisma.StringFilter<"TestRun"> | string
  created_at?: Prisma.DateTimeFilter<"TestRun"> | Date | string
}, "id">

export type TestRunOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.TestRunCountOrderByAggregateInput
  _max?: Prisma.TestRunMaxOrderByAggregateInput
  _min?: Prisma.TestRunMinOrderByAggregateInput
}

export type TestRunScalarWhereWithAggregatesInput = {
  AND?: Prisma.TestRunScalarWhereWithAggregatesInput | Prisma.TestRunScalarWhereWithAggregatesInput[]
  OR?: Prisma.TestRunScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TestRunScalarWhereWithAggregatesInput | Prisma.TestRunScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TestRun"> | string
  status?: Prisma.StringWithAggregatesFilter<"TestRun"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"TestRun"> | Date | string
}

export type TestRunCreateInput = {
  id?: string
  status: string
  created_at?: Date | string
}

export type TestRunUncheckedCreateInput = {
  id?: string
  status: string
  created_at?: Date | string
}

export type TestRunUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TestRunUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TestRunCreateManyInput = {
  id?: string
  status: string
  created_at?: Date | string
}

export type TestRunUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TestRunUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TestRunCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type TestRunMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type TestRunMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}



export type TestRunSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  created_at?: boolean
}, ExtArgs["result"]["testRun"]>

export type TestRunSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  created_at?: boolean
}, ExtArgs["result"]["testRun"]>

export type TestRunSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  created_at?: boolean
}, ExtArgs["result"]["testRun"]>

export type TestRunSelectScalar = {
  id?: boolean
  status?: boolean
  created_at?: boolean
}

export type TestRunOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "status" | "created_at", ExtArgs["result"]["testRun"]>

export type $TestRunPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TestRun"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    status: string
    created_at: Date
  }, ExtArgs["result"]["testRun"]>
  composites: {}
}

export type TestRunGetPayload<S extends boolean | null | undefined | TestRunDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TestRunPayload, S>

export type TestRunCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TestRunFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TestRunCountAggregateInputType | true
  }

export interface TestRunDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TestRun'], meta: { name: 'TestRun' } }
  /**
   * Find zero or one TestRun that matches the filter.
   * @param {TestRunFindUniqueArgs} args - Arguments to find a TestRun
   * @example
   * // Get one TestRun
   * const testRun = await prisma.testRun.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TestRunFindUniqueArgs>(args: Prisma.SelectSubset<T, TestRunFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TestRunClient<runtime.Types.Result.GetResult<Prisma.$TestRunPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TestRun that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TestRunFindUniqueOrThrowArgs} args - Arguments to find a TestRun
   * @example
   * // Get one TestRun
   * const testRun = await prisma.testRun.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TestRunFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TestRunFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TestRunClient<runtime.Types.Result.GetResult<Prisma.$TestRunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TestRun that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestRunFindFirstArgs} args - Arguments to find a TestRun
   * @example
   * // Get one TestRun
   * const testRun = await prisma.testRun.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TestRunFindFirstArgs>(args?: Prisma.SelectSubset<T, TestRunFindFirstArgs<ExtArgs>>): Prisma.Prisma__TestRunClient<runtime.Types.Result.GetResult<Prisma.$TestRunPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TestRun that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestRunFindFirstOrThrowArgs} args - Arguments to find a TestRun
   * @example
   * // Get one TestRun
   * const testRun = await prisma.testRun.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TestRunFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TestRunFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TestRunClient<runtime.Types.Result.GetResult<Prisma.$TestRunPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TestRuns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestRunFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TestRuns
   * const testRuns = await prisma.testRun.findMany()
   * 
   * // Get first 10 TestRuns
   * const testRuns = await prisma.testRun.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const testRunWithIdOnly = await prisma.testRun.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TestRunFindManyArgs>(args?: Prisma.SelectSubset<T, TestRunFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TestRunPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TestRun.
   * @param {TestRunCreateArgs} args - Arguments to create a TestRun.
   * @example
   * // Create one TestRun
   * const TestRun = await prisma.testRun.create({
   *   data: {
   *     // ... data to create a TestRun
   *   }
   * })
   * 
   */
  create<T extends TestRunCreateArgs>(args: Prisma.SelectSubset<T, TestRunCreateArgs<ExtArgs>>): Prisma.Prisma__TestRunClient<runtime.Types.Result.GetResult<Prisma.$TestRunPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TestRuns.
   * @param {TestRunCreateManyArgs} args - Arguments to create many TestRuns.
   * @example
   * // Create many TestRuns
   * const testRun = await prisma.testRun.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TestRunCreateManyArgs>(args?: Prisma.SelectSubset<T, TestRunCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TestRuns and returns the data saved in the database.
   * @param {TestRunCreateManyAndReturnArgs} args - Arguments to create many TestRuns.
   * @example
   * // Create many TestRuns
   * const testRun = await prisma.testRun.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TestRuns and only return the `id`
   * const testRunWithIdOnly = await prisma.testRun.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TestRunCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TestRunCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TestRunPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TestRun.
   * @param {TestRunDeleteArgs} args - Arguments to delete one TestRun.
   * @example
   * // Delete one TestRun
   * const TestRun = await prisma.testRun.delete({
   *   where: {
   *     // ... filter to delete one TestRun
   *   }
   * })
   * 
   */
  delete<T extends TestRunDeleteArgs>(args: Prisma.SelectSubset<T, TestRunDeleteArgs<ExtArgs>>): Prisma.Prisma__TestRunClient<runtime.Types.Result.GetResult<Prisma.$TestRunPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TestRun.
   * @param {TestRunUpdateArgs} args - Arguments to update one TestRun.
   * @example
   * // Update one TestRun
   * const testRun = await prisma.testRun.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TestRunUpdateArgs>(args: Prisma.SelectSubset<T, TestRunUpdateArgs<ExtArgs>>): Prisma.Prisma__TestRunClient<runtime.Types.Result.GetResult<Prisma.$TestRunPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TestRuns.
   * @param {TestRunDeleteManyArgs} args - Arguments to filter TestRuns to delete.
   * @example
   * // Delete a few TestRuns
   * const { count } = await prisma.testRun.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TestRunDeleteManyArgs>(args?: Prisma.SelectSubset<T, TestRunDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TestRuns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestRunUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TestRuns
   * const testRun = await prisma.testRun.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TestRunUpdateManyArgs>(args: Prisma.SelectSubset<T, TestRunUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TestRuns and returns the data updated in the database.
   * @param {TestRunUpdateManyAndReturnArgs} args - Arguments to update many TestRuns.
   * @example
   * // Update many TestRuns
   * const testRun = await prisma.testRun.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TestRuns and only return the `id`
   * const testRunWithIdOnly = await prisma.testRun.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TestRunUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TestRunUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TestRunPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TestRun.
   * @param {TestRunUpsertArgs} args - Arguments to update or create a TestRun.
   * @example
   * // Update or create a TestRun
   * const testRun = await prisma.testRun.upsert({
   *   create: {
   *     // ... data to create a TestRun
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TestRun we want to update
   *   }
   * })
   */
  upsert<T extends TestRunUpsertArgs>(args: Prisma.SelectSubset<T, TestRunUpsertArgs<ExtArgs>>): Prisma.Prisma__TestRunClient<runtime.Types.Result.GetResult<Prisma.$TestRunPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TestRuns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestRunCountArgs} args - Arguments to filter TestRuns to count.
   * @example
   * // Count the number of TestRuns
   * const count = await prisma.testRun.count({
   *   where: {
   *     // ... the filter for the TestRuns we want to count
   *   }
   * })
  **/
  count<T extends TestRunCountArgs>(
    args?: Prisma.Subset<T, TestRunCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TestRunCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TestRun.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestRunAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TestRunAggregateArgs>(args: Prisma.Subset<T, TestRunAggregateArgs>): Prisma.PrismaPromise<GetTestRunAggregateType<T>>

  /**
   * Group by TestRun.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TestRunGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TestRunGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TestRunGroupByArgs['orderBy'] }
      : { orderBy?: TestRunGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TestRunGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTestRunGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TestRun model
 */
readonly fields: TestRunFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TestRun.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TestRunClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TestRun model
 */
export interface TestRunFieldRefs {
  readonly id: Prisma.FieldRef<"TestRun", 'String'>
  readonly status: Prisma.FieldRef<"TestRun", 'String'>
  readonly created_at: Prisma.FieldRef<"TestRun", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TestRun findUnique
 */
export type TestRunFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
  /**
   * Filter, which TestRun to fetch.
   */
  where: Prisma.TestRunWhereUniqueInput
}

/**
 * TestRun findUniqueOrThrow
 */
export type TestRunFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
  /**
   * Filter, which TestRun to fetch.
   */
  where: Prisma.TestRunWhereUniqueInput
}

/**
 * TestRun findFirst
 */
export type TestRunFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
  /**
   * Filter, which TestRun to fetch.
   */
  where?: Prisma.TestRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TestRuns to fetch.
   */
  orderBy?: Prisma.TestRunOrderByWithRelationInput | Prisma.TestRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TestRuns.
   */
  cursor?: Prisma.TestRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TestRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TestRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TestRuns.
   */
  distinct?: Prisma.TestRunScalarFieldEnum | Prisma.TestRunScalarFieldEnum[]
}

/**
 * TestRun findFirstOrThrow
 */
export type TestRunFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
  /**
   * Filter, which TestRun to fetch.
   */
  where?: Prisma.TestRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TestRuns to fetch.
   */
  orderBy?: Prisma.TestRunOrderByWithRelationInput | Prisma.TestRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TestRuns.
   */
  cursor?: Prisma.TestRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TestRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TestRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TestRuns.
   */
  distinct?: Prisma.TestRunScalarFieldEnum | Prisma.TestRunScalarFieldEnum[]
}

/**
 * TestRun findMany
 */
export type TestRunFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
  /**
   * Filter, which TestRuns to fetch.
   */
  where?: Prisma.TestRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TestRuns to fetch.
   */
  orderBy?: Prisma.TestRunOrderByWithRelationInput | Prisma.TestRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TestRuns.
   */
  cursor?: Prisma.TestRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TestRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TestRuns.
   */
  skip?: number
  distinct?: Prisma.TestRunScalarFieldEnum | Prisma.TestRunScalarFieldEnum[]
}

/**
 * TestRun create
 */
export type TestRunCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
  /**
   * The data needed to create a TestRun.
   */
  data: Prisma.XOR<Prisma.TestRunCreateInput, Prisma.TestRunUncheckedCreateInput>
}

/**
 * TestRun createMany
 */
export type TestRunCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TestRuns.
   */
  data: Prisma.TestRunCreateManyInput | Prisma.TestRunCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TestRun createManyAndReturn
 */
export type TestRunCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
  /**
   * The data used to create many TestRuns.
   */
  data: Prisma.TestRunCreateManyInput | Prisma.TestRunCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TestRun update
 */
export type TestRunUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
  /**
   * The data needed to update a TestRun.
   */
  data: Prisma.XOR<Prisma.TestRunUpdateInput, Prisma.TestRunUncheckedUpdateInput>
  /**
   * Choose, which TestRun to update.
   */
  where: Prisma.TestRunWhereUniqueInput
}

/**
 * TestRun updateMany
 */
export type TestRunUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TestRuns.
   */
  data: Prisma.XOR<Prisma.TestRunUpdateManyMutationInput, Prisma.TestRunUncheckedUpdateManyInput>
  /**
   * Filter which TestRuns to update
   */
  where?: Prisma.TestRunWhereInput
  /**
   * Limit how many TestRuns to update.
   */
  limit?: number
}

/**
 * TestRun updateManyAndReturn
 */
export type TestRunUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
  /**
   * The data used to update TestRuns.
   */
  data: Prisma.XOR<Prisma.TestRunUpdateManyMutationInput, Prisma.TestRunUncheckedUpdateManyInput>
  /**
   * Filter which TestRuns to update
   */
  where?: Prisma.TestRunWhereInput
  /**
   * Limit how many TestRuns to update.
   */
  limit?: number
}

/**
 * TestRun upsert
 */
export type TestRunUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
  /**
   * The filter to search for the TestRun to update in case it exists.
   */
  where: Prisma.TestRunWhereUniqueInput
  /**
   * In case the TestRun found by the `where` argument doesn't exist, create a new TestRun with this data.
   */
  create: Prisma.XOR<Prisma.TestRunCreateInput, Prisma.TestRunUncheckedCreateInput>
  /**
   * In case the TestRun was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TestRunUpdateInput, Prisma.TestRunUncheckedUpdateInput>
}

/**
 * TestRun delete
 */
export type TestRunDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
  /**
   * Filter which TestRun to delete.
   */
  where: Prisma.TestRunWhereUniqueInput
}

/**
 * TestRun deleteMany
 */
export type TestRunDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TestRuns to delete
   */
  where?: Prisma.TestRunWhereInput
  /**
   * Limit how many TestRuns to delete.
   */
  limit?: number
}

/**
 * TestRun without action
 */
export type TestRunDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TestRun
   */
  select?: Prisma.TestRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TestRun
   */
  omit?: Prisma.TestRunOmit<ExtArgs> | null
}
