import type { BrainEdge, BrainGraphSummary, BrainNode, BuiltBrainGraph } from "../_types/brain.types";

export const brainMockNodes: BrainNode[] = [
  {
    id: "company:testing-company",
    type: "company",
    module: "Contexto",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Testing Company",
    description: "Empresa raiz do contexto permitido neste recorte do Brain.",
    status: "ok",
    size: "lg",
    information: "Testing Company organiza projetos, modulos e conhecimento operacional conforme o perfil do usuario.",
    generatedBy: "system",
  },
  {
    id: "project:quality-control",
    type: "project",
    module: "Contexto",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Quality Control",
    description: "Projeto principal de QA conectado a solicitacoes, defeitos, automacao, documentos e logs.",
    status: "ok",
    size: "lg",
    information: "Quality Control e o projeto onde o Brain relaciona modulos, eventos e informacoes formadas.",
    generatedBy: "system",
  },
  {
    id: "module:requests",
    type: "module",
    module: "Solicitacoes",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Solicitações",
    description: "Pedidos de acesso, revisao, decisao, e-mails e logs administrativos.",
    status: "ok",
    size: "lg",
    information: "Solicitações conectam pessoas, perfis, status, decisões e evidências de auditoria.",
    actions: ["Abrir modulo relacionado", "Mostrar nos de solicitacoes"],
  },
  {
    id: "request:barbara-support",
    type: "access_request",
    module: "Solicitacoes",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Solicitação Barbara",
    description: "Pedido de acesso para administrador recusado apos revisao.",
    status: "warning",
    size: "md",
    information: "Barbara abriu uma solicitacao de administrador, a solicitacao esta recusada e possui log pendente de evidencia.",
    createdBy: "Barbara",
    createdAt: new Date().toISOString(),
    generatedBy: "user",
    missingKnowledge: ["Vincular e-mail de recusa ao grafo real."],
    actions: ["Abrir modulo relacionado", "Explicar conexoes"],
  },
  {
    id: "person:barbara",
    type: "person",
    module: "Usuarios",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Barbara",
    description: "Pessoa solicitante do acesso de administrador.",
    status: "ok",
    size: "sm",
  },
  {
    id: "profile:support",
    type: "permission",
    module: "Permissoes",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Administrador",
    description: "Perfil solicitado, depende de permissao efetiva e escopo de empresa.",
    status: "pending",
    size: "sm",
    missingKnowledge: ["Mapear matriz de permissao do perfil no Brain."],
  },
  {
    id: "status:rejected",
    type: "status",
    module: "Solicitacoes",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Recusada",
    description: "Estado final de solicitacao negada pelo revisor.",
    status: "warning",
    size: "sm",
  },
  {
    id: "module:defects",
    type: "module",
    module: "Defeitos",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Defeitos",
    description: "Ocorrencias abertas, responsaveis, status, evidencias, comentarios e logs.",
    status: "ok",
    size: "lg",
    information: "Defeitos conectam ocorrencia, pessoa que abriu, status, evidencia, comentarios e historico.",
    actions: ["Abrir modulo relacionado", "Mostrar defeitos abertos"],
  },
  {
    id: "defect:bug-123",
    type: "defect",
    module: "Defeitos",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "BUG-123 aberto",
    description: "Defeito aberto durante validacao de regressao.",
    status: "ok",
    size: "md",
    information: "O defeito BUG-123 foi aberto por Ana Paula, esta com status Aberto, pertence ao modulo Defeitos e possui logs vinculados.",
    createdBy: "Ana Paula",
    createdAt: new Date().toISOString(),
    generatedBy: "user",
    actions: ["Abrir modulo relacionado", "Explicar conexoes"],
  },
  {
    id: "person:ana-paula",
    type: "person",
    module: "Usuarios",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Ana Paula",
    description: "Pessoa que abriu o defeito BUG-123.",
    status: "ok",
    size: "sm",
  },
  {
    id: "status:open",
    type: "status",
    module: "Defeitos",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Aberto",
    description: "Status operacional do defeito.",
    status: "ok",
    size: "sm",
  },
  {
    id: "comment:initial-report",
    type: "comment",
    module: "Defeitos",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Comentário inicial",
    description: "Relato inicial do problema com contexto da validacao.",
    status: "ok",
    size: "sm",
  },
  {
    id: "log:bug-123-created",
    type: "log",
    module: "Logs",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Log de abertura",
    description: "Registro de criacao do defeito no historico.",
    status: "ok",
    size: "sm",
  },
  {
    id: "module:automation",
    type: "module",
    module: "Automacao",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Automação",
    description: "Casos automatizados, scripts, execucoes, resultados e falhas.",
    status: "pending",
    size: "lg",
    missingKnowledge: ["Conectar execucoes reais de Playwright ao grafo."],
  },
  {
    id: "automation:login-regression",
    type: "automation",
    module: "Automacao",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Regressao de login",
    description: "Caso automatizado para fluxo de login e solicitacao de acesso.",
    status: "pending",
    size: "md",
    information: "A automacao de login depende de script, execucao e resultado para formar uma informacao confiavel.",
    generatedBy: "automation",
    missingKnowledge: ["Vincular ultima execucao e falha real."],
  },
  {
    id: "testcase:login-access",
    type: "test_case",
    module: "Automacao",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Caso Login + Acesso",
    description: "Caso de teste usado como conhecimento de origem para a automacao.",
    status: "ok",
    size: "sm",
  },
  {
    id: "module:documents",
    type: "module",
    module: "Documentos",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Documentos",
    description: "Base documental, categorias, autores e ultima atualizacao.",
    status: "pending",
    size: "lg",
    missingKnowledge: ["Indexar documentos em memoria semantica."],
  },
  {
    id: "document:access-policy",
    type: "document",
    module: "Documentos",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Politica de acesso",
    description: "Documento que explica criterios para aprovar ou recusar acessos.",
    status: "pending",
    size: "md",
    missingKnowledge: ["Extrair secoes e relacionar com decisoes."],
  },
  {
    id: "module:companies",
    type: "module",
    module: "Empresas",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Empresas",
    description: "Identidade institucional, usuarios vinculados e integracoes por empresa.",
    status: "ok",
    size: "lg",
    information: "Empresas conecta solicitacoes aprovadas, cadastro institucional, BrasilAPI, Qase, Jira e usuarios vinculados.",
  },
  {
    id: "integration:brasilapi-mock",
    type: "integration",
    module: "Empresas",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "BrasilAPI CNPJ",
    description: "Consulta de CNPJ usada para preencher identidade institucional da empresa.",
    status: "ok",
    size: "md",
    metadata: { provider: "BrasilAPI", route: "/api/public/company-lookup/cnpj" },
  },
  {
    id: "module:users",
    type: "module",
    module: "Usuarios",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Usuarios",
    description: "Pessoas, perfis, empresas e permissoes vinculadas.",
    status: "ok",
    size: "lg",
  },
  {
    id: "module:permissions",
    type: "module",
    module: "Permissoes",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Permissões",
    description: "Matriz efetiva de acesso por modulo, perfil e empresa.",
    status: "pending",
    size: "lg",
    missingKnowledge: ["Expor explicacao de permissao por rota."],
  },
  {
    id: "module:logs",
    type: "module",
    module: "Logs",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "Logs",
    description: "Eventos, trilhas de auditoria e evidencias temporais.",
    status: "missing",
    size: "lg",
    missingKnowledge: ["Completar vinculos de logs com entidades de negocio."],
  },
  {
    id: "entity:orphan-email",
    type: "email",
    module: "Logs",
    companyId: "company_testing",
    companyName: "Testing Company",
    projectId: "project_qc",
    projectName: "Quality Control",
    label: "E-mail sem vinculo",
    description: "Conhecimento isolado que ainda nao forma informacao com outro no.",
    status: "missing",
    size: "sm",
    missingKnowledge: ["Conectar e-mail a solicitacao, pessoa ou decisao."],
  },
];

export const brainMockEdges: BrainEdge[] = [
  { id: "company-project-qc", source: "company:testing-company", target: "project:quality-control", label: "possui projeto", type: "belongs_to_project", status: "ok" },
  { id: "qc-requests", source: "project:quality-control", target: "module:requests", label: "organiza modulo", type: "belongs_to_module", status: "ok" },
  { id: "qc-defects", source: "project:quality-control", target: "module:defects", label: "organiza modulo", type: "belongs_to_module", status: "ok" },
  { id: "qc-automation", source: "project:quality-control", target: "module:automation", label: "organiza modulo", type: "belongs_to_module", status: "ok" },
  { id: "qc-documents", source: "project:quality-control", target: "module:documents", label: "organiza modulo", type: "belongs_to_module", status: "ok" },
  { id: "qc-companies", source: "project:quality-control", target: "module:companies", label: "organiza modulo", type: "belongs_to_module", status: "ok" },
  { id: "requests-contains-barbara", source: "module:requests", target: "request:barbara-support", label: "contem", type: "contains", status: "ok" },
  { id: "requests-companies-flow", source: "module:requests", target: "module:companies", label: "aprova empresas", type: "generates", status: "ok" },
  { id: "requests-users-flow", source: "module:requests", target: "module:users", label: "aprova usuarios", type: "generates", status: "ok" },
  { id: "barbara-created-request", source: "request:barbara-support", target: "person:barbara", label: "foi aberto por", type: "created_by", status: "ok" },
  { id: "barbara-profile", source: "request:barbara-support", target: "profile:support", label: "pede perfil", type: "permission", status: "pending" },
  { id: "barbara-status", source: "request:barbara-support", target: "status:rejected", label: "esta com status", type: "has_status", status: "warning" },
  { id: "defects-contains-bug", source: "module:defects", target: "defect:bug-123", label: "contem", type: "contains", status: "ok" },
  { id: "bug-created-by", source: "defect:bug-123", target: "person:ana-paula", label: "foi aberto por", type: "created_by", status: "ok" },
  { id: "bug-status", source: "defect:bug-123", target: "status:open", label: "esta com status", type: "has_status", status: "ok" },
  { id: "bug-comment", source: "defect:bug-123", target: "comment:initial-report", label: "possui comentario", type: "has_comment", status: "ok" },
  { id: "bug-log", source: "defect:bug-123", target: "log:bug-123-created", label: "possui log", type: "has_log", status: "ok" },
  { id: "automation-contains-login", source: "module:automation", target: "automation:login-regression", label: "contem", type: "contains", status: "pending" },
  { id: "automation-testcase", source: "automation:login-regression", target: "testcase:login-access", label: "depende do caso", type: "depends_on", status: "ok" },
  { id: "documents-policy", source: "module:documents", target: "document:access-policy", label: "contem", type: "contains", status: "pending" },
  { id: "policy-permission", source: "document:access-policy", target: "profile:support", label: "explica permissao", type: "generates", status: "pending" },
  { id: "companies-brasilapi", source: "module:companies", target: "integration:brasilapi-mock", label: "consulta CNPJ", type: "depends_on", status: "ok" },
  { id: "users-barbara", source: "module:users", target: "person:barbara", label: "conhece pessoa", type: "contains", status: "ok" },
  { id: "users-ana", source: "module:users", target: "person:ana-paula", label: "conhece pessoa", type: "contains", status: "ok" },
  { id: "permissions-profile", source: "module:permissions", target: "profile:support", label: "governa", type: "permission", status: "pending" },
  { id: "logs-bug-log", source: "module:logs", target: "log:bug-123-created", label: "registra", type: "contains", status: "ok" },
];

export function buildMockBrainGraph(): BuiltBrainGraph {
  const connected = new Set(brainMockEdges.flatMap((edge) => [edge.source, edge.target]));
  const pendingMappings = brainMockNodes
    .flatMap((node) => node.missingKnowledge ?? [])
    .filter(Boolean);

  const summary: BrainGraphSummary = {
    totalNodes: brainMockNodes.length,
    totalEdges: brainMockEdges.length,
    totalModules: new Set(brainMockNodes.map((node) => node.module)).size,
    companies: new Set(brainMockNodes.map((node) => node.companyId).filter(Boolean)).size,
    projects: new Set(brainMockNodes.map((node) => node.projectId).filter(Boolean)).size,
    modules: new Set(brainMockNodes.map((node) => node.module)).size,
    accessRequestNodes: brainMockNodes.filter((node) => node.type === "access_request").length,
    requestsWithoutNode: 1,
    orphanNodes: brainMockNodes.filter((node) => !connected.has(node.id)).length,
    pendingNodes: brainMockNodes.filter((node) => ["pending", "missing", "warning", "error", "orphan"].includes(node.status)).length,
    missingKnowledge: pendingMappings.length,
    eventsToday: 6,
    generatedByBrain: brainMockNodes.filter((node) => node.generatedBy === "brain").length,
    generatedByAutomation: brainMockNodes.filter((node) => node.generatedBy === "automation").length,
    generatedByUsers: brainMockNodes.filter((node) => node.generatedBy === "user").length,
    logsLinked: brainMockNodes.filter((node) => node.type === "log" && node.status === "ok").length,
    pendingMappings,
  };

  return {
    nodes: brainMockNodes,
    edges: brainMockEdges,
    summary,
    requests: [],
    removalHistory: [],
    auditLogs: [],
  };
}
