export type Role = 'admin' | 'dev' | 'company' | 'user' | 'support';

export const ROLE_DEFAULTS: Record<Role, Record<string, string[]>> = {
  admin: {
    dashboard: ['view', 'create', 'edit', 'delete', 'export', 'assign'],
    applications: ['view', 'create', 'edit', 'delete', 'export'],
    releases: ['view', 'create', 'edit', 'delete'],
    runs: ['view', 'create', 'edit'],
    defects: ['view', 'create', 'edit', 'delete'],
    tickets: ['view', 'create', 'edit', 'delete'],
    users: ['view', 'create', 'edit', 'delete'],
    notes: ['view', 'create', 'edit', 'delete'],
    notifications: ['view', 'create'],
    audit: ['view', 'export'],
    settings: ['view', 'edit'],
  },
  dev: {
    dashboard: ['view'],
    applications: ['view', 'edit'],
    releases: ['view', 'create', 'edit'],
    runs: ['view', 'create'],
    defects: ['view', 'create', 'edit'],
    tickets: ['view'],
    users: ['view'],
    notes: ['view', 'create'],
    notifications: ['view'],
    audit: [],
    settings: [],
  },
  company: {
    dashboard: ['view'],
    applications: ['view'],
    releases: ['view'],
    runs: ['view'],
    defects: ['view', 'create'],
    tickets: ['view', 'create'],
    users: ['view'],
    notes: ['view', 'create'],
    notifications: ['view'],
    audit: [],
    settings: [],
  },
  user: {
    dashboard: ['view'],
    applications: ['view'],
    releases: ['view'],
    runs: ['view'],
    defects: ['view'],
    tickets: ['view', 'create'],
    users: [],
    notes: ['view', 'create'],
    notifications: ['view'],
    audit: [],
    settings: [],
  },
  support: {
    dashboard: ['view'],
    tickets: ['view', 'create', 'edit'],
    users: ['view'],
    notifications: ['view'],
  },
};
