import type { SystemModuleDefinition } from "./navigation.types";

export const SYSTEM_MODULES = [
  {
    id: "empresas",
    name: "Empresas",
    description: "Cadastro, contexto e operação das empresas atendidas.",
    mainRoute: "/admin/clients",
    basePermission: { moduleId: "applications", action: "view" },
    status: "ativo",
  },
  {
    id: "usuarios",
    name: "Usuários",
    description: "Gestão de usuários internos e vinculados a empresas.",
    mainRoute: "/admin/users",
    basePermission: { moduleId: "users", action: "view" },
    status: "ativo",
  },
  {
    id: "permissoes",
    name: "Permissões",
    description: "Perfis, matriz de acesso e sobrescritas por usuário.",
    mainRoute: "/admin/users/permissions",
    basePermission: { moduleId: "permissions", action: "view" },
    status: "parcial",
  },
  {
    id: "testes-manuais",
    name: "Testes Manuais",
    description: "Casos, planos, execuções, releases e defeitos.",
    mainRoute: "/casos-de-teste",
    basePermission: { moduleId: "test_repository", action: "read" },
    status: "ativo",
  },
  {
    id: "automacao",
    name: "Automação",
    description: "Playwright, execuções, ativos, scripts e ferramentas.",
    mainRoute: "/automacoes",
    basePermission: { moduleId: "playwright", action: "read" },
    status: "parcial",
  },
  {
    id: "brain",
    name: "Brain",
    description: "Grafo de conhecimento e recursos internos do Brain.",
    mainRoute: "/brain",
    basePermission: { moduleId: "ai", action: "view" },
    status: "parcial",
  },
  {
    id: "assistente",
    name: "Assistente",
    description: "Consulta assistida e ações apoiadas por IA.",
    mainRoute: "/brain",
    basePermission: { moduleId: "ai", action: "use" },
    status: "parcial",
  },
  {
    id: "chat",
    name: "Chat",
    description: "Conversas e contatos entre usuários da plataforma.",
    mainRoute: "/chat",
    basePermission: null,
    status: "parcial",
  },
  {
    id: "suporte",
    name: "Suporte",
    description: "Abertura, acompanhamento e operação de chamados.",
    mainRoute: "/suporte",
    basePermission: { moduleId: "support", action: "view" },
    status: "ativo",
  },
  {
    id: "solicitacoes",
    name: "Solicitações",
    description: "Solicitações de acesso e alterações administrativas.",
    mainRoute: "/solicitacoes",
    basePermission: { moduleId: "access_requests", action: "view" },
    status: "parcial",
  },
  {
    id: "documentos",
    name: "Documentos",
    description: "Central, repositório e documentação da plataforma.",
    mainRoute: "/documentos",
    basePermission: { moduleId: "notes", action: "view" },
    status: "parcial",
  },
  {
    id: "dashboards",
    name: "Dashboards",
    description: "Indicadores globais, administrativos e de empresa.",
    mainRoute: "/dashboard",
    basePermission: { moduleId: "dashboard", action: "view" },
    status: "parcial",
  },
  {
    id: "operacao",
    name: "Operação",
    description: "Visões operacionais, busca e métricas consolidadas.",
    mainRoute: "/operacoes",
    basePermission: { moduleId: "dashboard", action: "view" },
    status: "parcial",
  },
  {
    id: "configuracoes",
    name: "Configurações",
    description: "Perfil, preferências e administração da conta.",
    mainRoute: "/settings/profile",
    basePermission: { moduleId: "settings", action: "view" },
    status: "parcial",
  },
] as const satisfies readonly SystemModuleDefinition[];

export const SYSTEM_MODULE_BY_ID = new Map(
  SYSTEM_MODULES.map((moduleDefinition) => [moduleDefinition.id, moduleDefinition]),
);
