import { SYSTEM_ROLES, type SystemRole } from "@/lib/auth/roles";
import type { SystemRouteDefinition } from "./navigation.types";

const ALL_PROFILES: SystemRole[] = [
  SYSTEM_ROLES.LEADER_TC,
  SYSTEM_ROLES.TECHNICAL_SUPPORT,
  SYSTEM_ROLES.TESTING_COMPANY_USER,
  SYSTEM_ROLES.EMPRESA,
  SYSTEM_ROLES.COMPANY_USER,
];

const INTERNAL_PROFILES: SystemRole[] = [
  SYSTEM_ROLES.LEADER_TC,
  SYSTEM_ROLES.TECHNICAL_SUPPORT,
  SYSTEM_ROLES.TESTING_COMPANY_USER,
];

const ADMIN_PROFILES: SystemRole[] = [
  SYSTEM_ROLES.LEADER_TC,
  SYSTEM_ROLES.TECHNICAL_SUPPORT,
];

const COMPANY_PROFILES: SystemRole[] = [
  SYSTEM_ROLES.LEADER_TC,
  SYSTEM_ROLES.TECHNICAL_SUPPORT,
  SYSTEM_ROLES.TESTING_COMPANY_USER,
  SYSTEM_ROLES.EMPRESA,
  SYSTEM_ROLES.COMPANY_USER,
];

export const SYSTEM_ROUTES = [
  {
    id: "home.principal",
    moduleId: "dashboards",
    path: "/home",
    label: "Home",
    description: "Entrada principal adaptada ao perfil autenticado.",
    requiredPermission: { moduleId: "dashboard", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/home/page.tsx",
  },
  {
    id: "empresas.listagem",
    moduleId: "empresas",
    path: "/admin/clients",
    label: "Listagem de empresas",
    description: "Cadastro e consulta administrativa das empresas.",
    requiredPermission: { moduleId: "applications", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/admin/clients/page.tsx",
  },
  {
    id: "empresas.buscar",
    moduleId: "empresas",
    path: "/admin/clients?focus=search",
    label: "Buscar empresa",
    description: "Abre a listagem administrativa com foco na busca.",
    requiredPermission: { moduleId: "applications", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/admin/clients/page.tsx",
  },
  {
    id: "empresas.criar",
    moduleId: "empresas",
    path: "/admin/clients?modal=create",
    label: "Criar empresa",
    description: "Abre o cadastro de uma empresa.",
    requiredPermission: { moduleId: "applications", action: "create" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/admin/clients/page.tsx",
  },
  {
    id: "empresas.portal",
    moduleId: "empresas",
    path: "/empresas/[slug]/home",
    label: "Portal da empresa",
    description: "Entrada principal do contexto de uma empresa.",
    requiredPermission: { moduleId: "dashboard", action: "view" },
    expectedProfiles: COMPANY_PROFILES,
    status: "ativo",
    mainFile: "app/empresas/[slug]/home/page.tsx",
  },
  {
    id: "empresas.aplicacoes",
    moduleId: "empresas",
    path: "/empresas/[slug]/aplicacoes",
    label: "Aplicações da empresa",
    description: "Aplicações e integrações vinculadas à empresa.",
    requiredPermission: { moduleId: "applications", action: "view" },
    expectedProfiles: COMPANY_PROFILES,
    status: "ativo",
    mainFile: "app/empresas/[slug]/aplicacoes/page.tsx",
  },
  {
    id: "usuarios.listagem",
    moduleId: "usuarios",
    path: "/admin/users",
    label: "Gestão de usuários",
    description: "Listagem, criação e manutenção dos usuários.",
    requiredPermission: { moduleId: "users", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/admin/users/page.tsx",
  },
  {
    id: "usuarios.criar-lider",
    moduleId: "usuarios",
    path: "/admin/users?modal=create&role=leader_tc",
    label: "Criar Líder TC",
    description: "Abre o cadastro de um Líder TC.",
    requiredPermission: { moduleId: "users", action: "create" },
    expectedProfiles: [SYSTEM_ROLES.LEADER_TC],
    status: "ativo",
    mainFile: "app/admin/users/page.tsx",
  },
  {
    id: "usuarios.criar-suporte",
    moduleId: "usuarios",
    path: "/admin/users?modal=create&role=technical_support",
    label: "Criar Suporte Técnico",
    description: "Abre o cadastro de um usuário de suporte.",
    requiredPermission: { moduleId: "users", action: "create" },
    expectedProfiles: [SYSTEM_ROLES.LEADER_TC],
    status: "ativo",
    mainFile: "app/admin/users/page.tsx",
  },
  {
    id: "usuarios.criar-usuario-tc",
    moduleId: "usuarios",
    path: "/admin/users?modal=create&role=testing_company_user",
    label: "Criar Usuário TC",
    description: "Abre o cadastro de um usuário interno.",
    requiredPermission: { moduleId: "users", action: "create" },
    expectedProfiles: [SYSTEM_ROLES.LEADER_TC],
    status: "ativo",
    mainFile: "app/admin/users/page.tsx",
  },
  {
    id: "usuarios.criar-usuario-empresa",
    moduleId: "usuarios",
    path: "/admin/users?modal=create&role=company_user",
    label: "Criar Usuário da Empresa",
    description: "Abre o cadastro de um usuário vinculado à empresa.",
    requiredPermission: { moduleId: "users", action: "create" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/admin/users/page.tsx",
  },
  {
    id: "permissoes.matriz",
    moduleId: "permissoes",
    path: "/admin/users/permissions",
    label: "Matriz de permissões",
    description: "Perfil base e permissões efetivas por usuário.",
    requiredPermission: { moduleId: "permissions", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/admin/users/permissions/page.tsx",
  },
  {
    id: "permissoes.atalho-admin",
    moduleId: "permissoes",
    path: "/admin/permissoes",
    label: "Permissões administrativas",
    description: "Entrada administrativa anterior para permissões.",
    requiredPermission: { moduleId: "permissions", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "legado",
    mainFile: "app/admin/permissoes/page.tsx",
    notes: "Manter enquanto houver links apontando para esta rota; consolidar com a matriz principal.",
  },
  {
    id: "testes-manuais.casos",
    moduleId: "testes-manuais",
    path: "/casos-de-teste",
    label: "Casos de teste",
    description: "Repositório central de casos de teste.",
    requiredPermission: { moduleId: "test_repository", action: "read" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/casos-de-teste/page.tsx",
  },
  {
    id: "testes-manuais.planos",
    moduleId: "testes-manuais",
    path: "/empresas/[slug]/planos-de-teste",
    label: "Planos de teste",
    description: "Planejamento de ciclos de teste por empresa.",
    requiredPermission: { moduleId: "test_plan", action: "read" },
    expectedProfiles: COMPANY_PROFILES,
    status: "ativo",
    mainFile: "app/empresas/[slug]/planos-de-teste/page.tsx",
  },
  {
    id: "testes-manuais.runs",
    moduleId: "testes-manuais",
    path: "/empresas/[slug]/runs",
    label: "Runs",
    description: "Execuções de teste no contexto da empresa.",
    requiredPermission: { moduleId: "test_run", action: "read" },
    expectedProfiles: COMPANY_PROFILES,
    status: "ativo",
    mainFile: "app/empresas/[slug]/runs/page.tsx",
  },
  {
    id: "testes-manuais.defeitos",
    moduleId: "testes-manuais",
    path: "/empresas/[slug]/defeitos",
    label: "Defeitos",
    description: "Registro e acompanhamento de defeitos da empresa.",
    requiredPermission: { moduleId: "defect_tracking", action: "read" },
    expectedProfiles: COMPANY_PROFILES,
    status: "parcial",
    mainFile: "app/empresas/[slug]/defeitos/page.tsx",
    notes: "Tela extensa e candidata a divisão incremental em componentes.",
  },
  {
    id: "testes-manuais.releases",
    moduleId: "testes-manuais",
    path: "/empresas/[slug]/releases",
    label: "Releases",
    description: "Releases e decisão de qualidade por empresa.",
    requiredPermission: { moduleId: "release_management", action: "read" },
    expectedProfiles: COMPANY_PROFILES,
    status: "ativo",
    mainFile: "app/empresas/[slug]/releases/page.tsx",
  },
  {
    id: "automacao.inicio",
    moduleId: "automacao",
    path: "/automacoes",
    label: "Central de automação",
    description: "Entrada do ambiente de automação.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "ativo",
    mainFile: "app/automacoes/page.tsx",
  },
  {
    id: "automacao.playwright",
    moduleId: "automacao",
    path: "/automacoes/playwright",
    label: "Playwright",
    description: "Criação e execução de automações Playwright.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "ativo",
    mainFile: "app/automacoes/playwright/page.tsx",
  },
  {
    id: "automacao.studio",
    moduleId: "automacao",
    path: "/automacoes/ui-studio",
    label: "UI Studio",
    description: "Ambiente visual para montagem de automações.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "parcial",
    mainFile: "app/automacoes/ui-studio/page.tsx",
    notes: "A implementação principal ainda está concentrada em AutomationStudio.tsx.",
  },
  {
    id: "automacao.execucoes",
    moduleId: "automacao",
    path: "/automacoes/execucoes",
    label: "Execuções automatizadas",
    description: "Histórico e estado das execuções automatizadas.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "ativo",
    mainFile: "app/automacoes/execucoes/page.tsx",
  },
  {
    id: "automacao.fluxos",
    moduleId: "automacao",
    path: "/automacoes/fluxos",
    label: "Fluxos automatizados",
    description: "Fluxos disponíveis para automação.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "ativo",
    mainFile: "app/automacoes/fluxos/page.tsx",
  },
  {
    id: "automacao.casos",
    moduleId: "automacao",
    path: "/automacoes/casos",
    label: "Casos automatizados",
    description: "Casos associados a automações.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "legado",
    mainFile: "app/automacoes/casos/page.tsx",
    notes: "A navegação canônica de casos manuais permanece em /casos-de-teste.",
  },
  {
    id: "automacao.scripts",
    moduleId: "automacao",
    path: "/automacoes/scripts",
    label: "Scripts",
    description: "Biblioteca de scripts de automação.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "ativo",
    mainFile: "app/automacoes/scripts/page.tsx",
  },
  {
    id: "automacao.ferramentas",
    moduleId: "automacao",
    path: "/automacoes/tools",
    label: "Ferramentas",
    description: "Ferramentas auxiliares de automação.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "ativo",
    mainFile: "app/automacoes/tools/page.tsx",
  },
  {
    id: "automacao.api-lab",
    moduleId: "automacao",
    path: "/automacoes/api-lab",
    label: "API Lab",
    description: "Ambiente para testar chamadas HTTP.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "ativo",
    mainFile: "app/automacoes/api-lab/page.tsx",
  },
  {
    id: "automacao.base64",
    moduleId: "automacao",
    path: "/automacoes/base64",
    label: "Base64 e encoders",
    description: "Ferramentas para codificação e transformação.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "ativo",
    mainFile: "app/automacoes/base64/page.tsx",
  },
  {
    id: "automacao.biblioteca",
    moduleId: "automacao",
    path: "/automacoes/base64?tab=library",
    label: "Biblioteca de arquivos",
    description: "Abre a biblioteca de ativos da automação.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "parcial",
    mainFile: "app/automacoes/base64/page.tsx",
  },
  {
    id: "automacao.logs",
    moduleId: "automacao",
    path: "/automacoes/logs",
    label: "Logs de automação",
    description: "Consulta dos registros das automações.",
    requiredPermission: { moduleId: "playwright", action: "read" },
    expectedProfiles: INTERNAL_PROFILES,
    status: "ativo",
    mainFile: "app/automacoes/logs/page.tsx",
  },
  {
    id: "brain.grafo",
    moduleId: "brain",
    path: "/brain",
    label: "Grafo do Brain",
    description: "Visualização do grafo de conhecimento.",
    requiredPermission: { moduleId: "ai", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/brain/page.tsx",
  },
  {
    id: "brain.admin",
    moduleId: "brain",
    path: "/admin/brain",
    label: "Administração do Brain",
    description: "Ferramentas internas de diagnóstico do Brain.",
    requiredPermission: { moduleId: "ai", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "oculto",
    mainFile: "app/admin/brain/page.tsx",
    notes: "Existe, mas não está no catálogo principal do menu.",
  },
  {
    id: "assistente.perguntar",
    moduleId: "assistente",
    path: "/brain/perguntar",
    label: "Perguntar ao assistente",
    description: "Conversa orientada pelo contexto do produto.",
    requiredPermission: { moduleId: "ai", action: "use" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/brain/perguntar/page.tsx",
  },
  {
    id: "chat.principal",
    moduleId: "chat",
    path: "/chat",
    label: "Chat",
    description: "Lista de conversas e troca de mensagens.",
    requiredPermission: null,
    expectedProfiles: ALL_PROFILES,
    status: "parcial",
    mainFile: "app/chat/page.tsx",
    notes: "A visibilidade ainda depende de perfil; não há permissão específica de chat na matriz.",
  },
  {
    id: "chat.buscar",
    moduleId: "chat",
    path: "/chat?focus=search",
    label: "Buscar conversa",
    description: "Abre o chat com foco na busca.",
    requiredPermission: null,
    expectedProfiles: ALL_PROFILES,
    status: "parcial",
    mainFile: "app/chat/page.tsx",
    notes: "A visibilidade ainda depende de perfil; não há permissão específica de chat na matriz.",
  },
  {
    id: "chat.conversas",
    moduleId: "chat",
    path: "/conversas",
    label: "Conversas",
    description: "Entrada alternativa para conversas.",
    requiredPermission: null,
    expectedProfiles: ALL_PROFILES,
    status: "legado",
    mainFile: "app/conversas/page.tsx",
    notes: "Avaliar consolidação com /chat.",
  },
  {
    id: "suporte.central",
    moduleId: "suporte",
    path: "/suporte",
    label: "Central de suporte",
    description: "Abertura e consulta de chamados.",
    requiredPermission: { moduleId: "support", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/suporte/page.tsx",
  },
  {
    id: "suporte.criar",
    moduleId: "suporte",
    path: "/suporte?modal=create",
    label: "Abrir chamado",
    description: "Abre o formulário de novo chamado.",
    requiredPermission: { moduleId: "support", action: "create" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/suporte/page.tsx",
  },
  {
    id: "suporte.kanban",
    moduleId: "suporte",
    path: "/suporte/kanban",
    label: "Kanban de suporte",
    description: "Andamento operacional dos chamados.",
    requiredPermission: { moduleId: "support", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/suporte/kanban/page.tsx",
  },
  {
    id: "suporte.chamados",
    moduleId: "suporte",
    path: "/chamados",
    label: "Chamados",
    description: "Visão ampla de chamados para perfis internos.",
    requiredPermission: { moduleId: "tickets", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/chamados/page.tsx",
  },
  {
    id: "suporte.meus-chamados",
    moduleId: "suporte",
    path: "/meus-chamados",
    label: "Meus chamados",
    description: "Chamados visíveis para o usuário autenticado.",
    requiredPermission: { moduleId: "tickets", action: "view_own" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/meus-chamados/page.tsx",
  },
  {
    id: "solicitacoes.listagem",
    moduleId: "solicitacoes",
    path: "/solicitacoes",
    label: "Solicitações",
    description: "Fila administrativa de solicitações.",
    requiredPermission: { moduleId: "access_requests", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/solicitacoes/page.tsx",
  },
  {
    id: "solicitacoes.buscar",
    moduleId: "solicitacoes",
    path: "/solicitacoes?focus=search",
    label: "Buscar solicitação",
    description: "Abre a fila de solicitações com foco na busca.",
    requiredPermission: { moduleId: "access_requests", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/solicitacoes/page.tsx",
  },
  {
    id: "solicitacoes.acessos-admin",
    moduleId: "solicitacoes",
    path: "/admin/access-requests",
    label: "Solicitações de acesso",
    description: "Fluxo administrativo detalhado de acessos.",
    requiredPermission: { moduleId: "access_requests", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "parcial",
    mainFile: "app/admin/access-requests/page.tsx",
    notes: "Convive com /solicitacoes e deve ter responsabilidade consolidada futuramente.",
  },
  {
    id: "documentos.central",
    moduleId: "documentos",
    path: "/documentos",
    label: "Central de documentos",
    description: "Acesso principal aos documentos.",
    requiredPermission: { moduleId: "notes", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/documentos/page.tsx",
  },
  {
    id: "documentos.repositorio",
    moduleId: "documentos",
    path: "/documentos/repositorio",
    label: "Repositório de documentos",
    description: "Organização e consulta do acervo.",
    requiredPermission: { moduleId: "notes", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/documentos/repositorio/page.tsx",
  },
  {
    id: "documentos.plataforma",
    moduleId: "documentos",
    path: "/docs/platform",
    label: "Documentação da plataforma",
    description: "Documentação técnica e funcional da plataforma.",
    requiredPermission: { moduleId: "notes", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "oculto",
    mainFile: "app/docs/platform/page.tsx",
    notes: "Rota existente fora do catálogo principal de documentos.",
  },
  {
    id: "dashboards.geral",
    moduleId: "dashboards",
    path: "/dashboard",
    label: "Dashboard geral",
    description: "Visão geral conforme o contexto do usuário.",
    requiredPermission: { moduleId: "dashboard", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/dashboard/page.tsx",
  },
  {
    id: "dashboards.admin",
    moduleId: "dashboards",
    path: "/admin/dashboard",
    label: "Dashboard administrativo",
    description: "Indicadores globais e ranking de empresas.",
    requiredPermission: { moduleId: "dashboard", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/admin/dashboard/page.tsx",
  },
  {
    id: "dashboards.empresa",
    moduleId: "dashboards",
    path: "/empresas/[slug]/dashboard",
    label: "Dashboard da empresa",
    description: "Indicadores de qualidade no contexto da empresa.",
    requiredPermission: { moduleId: "dashboard", action: "view" },
    expectedProfiles: COMPANY_PROFILES,
    status: "parcial",
    mainFile: "app/empresas/[slug]/dashboard/page.tsx",
    notes: "A implementação cliente é extensa e candidata a divisão incremental.",
  },
  {
    id: "operacao.inicio",
    moduleId: "operacao",
    path: "/operacoes",
    label: "Operações",
    description: "Entrada da área operacional.",
    requiredPermission: { moduleId: "dashboard", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/operacoes/page.tsx",
  },
  {
    id: "operacao.dashboard",
    moduleId: "operacao",
    path: "/operacoes/dashboard",
    label: "Dashboard operacional",
    description: "Resumo operacional do ambiente.",
    requiredPermission: { moduleId: "dashboard", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/operacoes/dashboard/page.tsx",
  },
  {
    id: "operacao.metricas",
    moduleId: "operacao",
    path: "/operacoes/metricas",
    label: "Métricas operacionais",
    description: "Métricas consolidadas da operação.",
    requiredPermission: { moduleId: "dashboard", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "ativo",
    mainFile: "app/operacoes/metricas/page.tsx",
  },
  {
    id: "operacao.busca",
    moduleId: "operacao",
    path: "/operacoes/buscar",
    label: "Busca operacional",
    description: "Busca transversal por empresas e itens operacionais.",
    requiredPermission: { moduleId: "applications", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/operacoes/buscar/page.tsx",
  },
  {
    id: "configuracoes.perfil",
    moduleId: "configuracoes",
    path: "/settings/profile",
    label: "Perfil",
    description: "Dados pessoais, preferências e segurança.",
    requiredPermission: { moduleId: "settings", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "parcial",
    mainFile: "app/settings/profile/page.tsx",
    notes: "Tela extensa e candidata a divisão incremental por seção.",
  },
  {
    id: "configuracoes.admin",
    moduleId: "configuracoes",
    path: "/settings/admin",
    label: "Configurações administrativas",
    description: "Configurações reservadas aos administradores.",
    requiredPermission: { moduleId: "settings", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "oculto",
    mainFile: "app/settings/admin/page.tsx",
  },
  {
    id: "configuracoes.auditoria",
    moduleId: "configuracoes",
    path: "/audit-logs?source=admin",
    label: "Logs de auditoria",
    description: "Eventos administrativos e alterações sensíveis.",
    requiredPermission: { moduleId: "audit", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/audit-logs/page.tsx",
  },
  {
    id: "configuracoes.mapa-sistema",
    moduleId: "configuracoes",
    path: "/admin/sistema/mapa",
    label: "Mapa do Sistema",
    description: "Governança de módulos, rotas e permissões.",
    requiredPermission: { moduleId: "permissions", action: "view" },
    expectedProfiles: ADMIN_PROFILES,
    status: "ativo",
    mainFile: "app/admin/sistema/mapa/page.tsx",
  },
  {
    id: "configuracoes.perfil-legado",
    moduleId: "configuracoes",
    path: "/profile",
    label: "Perfil legado",
    description: "Entrada anterior para dados do perfil.",
    requiredPermission: { moduleId: "settings", action: "view" },
    expectedProfiles: ALL_PROFILES,
    status: "legado",
    mainFile: "app/profile/page.tsx",
    notes: "Avaliar consolidação com /settings/profile.",
  },
] as const satisfies readonly SystemRouteDefinition[];

export const SYSTEM_ROUTE_BY_ID: ReadonlyMap<string, SystemRouteDefinition> = new Map(
  SYSTEM_ROUTES.map((routeDefinition) => [routeDefinition.id, routeDefinition]),
);
