import {
  FiActivity,
  FiAlertCircle,
  FiBarChart2,
  FiBook,
  FiBookmark,
  FiBookOpen,
  FiBox,
  FiBriefcase,
  FiCheckCircle,
  FiClipboard,
  FiClock,
  FiCode,
  FiColumns,
  FiCompass,
  FiCpu,
  FiDatabase,
  FiDownload,
  FiEye,
  FiFileText,
  FiFolder,
  FiGitBranch,
  FiGrid,
  FiHeadphones,
  FiHelpCircle,
  FiHome,
  FiImage,
  FiInbox,
  FiLayers,
  FiLayout,
  FiLink,
  FiList,
  FiLock,
  FiMessageCircle,
  FiMessageSquare,
  FiMonitor,
  FiPackage,
  FiPieChart,
  FiPlay,
  FiPlusCircle,
  FiSettings,
  FiShield,
  FiSliders,
  FiTool,
  FiUser,
  FiUserPlus,
  FiUsers,
  FiX,
  FiZap,
} from "react-icons/fi";

export type IconKey = string;

const registry: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  home: FiHome,
  compass: FiCompass,
  dashboard: FiCompass,
  grid: FiGrid,
  users: FiUsers,
  "user-plus": FiUserPlus,
  user: FiUser,
  headphones: FiHeadphones,
  monitor: FiMonitor,
  activity: FiActivity,
  "check-circle": FiCheckCircle,
  clipboard: FiClipboard,
  book: FiBook,
  "book-open": FiBookOpen,
  "alert-circle": FiAlertCircle,
  package: FiPackage,
  zap: FiZap,
  "help-circle": FiHelpCircle,
  columns: FiColumns,
  cpu: FiCpu,
  "message-circle": FiMessageCircle,
  "message-square": FiMessageSquare,
  shield: FiShield,
  "file-text": FiFileText,
  "bar-chart": FiBarChart2,
  briefcase: FiBriefcase,
  building: FiBriefcase,
  link: FiLink,
  layout: FiLayout,
  list: FiList,
  eye: FiEye,
  settings: FiSettings,
  sliders: FiSliders,
  code: FiCode,
  bookmark: FiBookmark,
  box: FiBox,
  clock: FiClock,
  database: FiDatabase,
  download: FiDownload,
  folder: FiFolder,
  "git-branch": FiGitBranch,
  image: FiImage,
  inbox: FiInbox,
  layers: FiLayers,
  lock: FiLock,
  "pie-chart": FiPieChart,
  play: FiPlay,
  "plus-circle": FiPlusCircle,
  tool: FiTool,
  x: FiX,
};

export function getIcon(key: string): React.ComponentType<{ size?: number; className?: string }> {
  return registry[key] ?? FiBox;
}
