import {
  FiActivity,
  FiAlertCircle,
  FiBarChart2,
  FiBook,
  FiBookmark,
  FiBox,
  FiBriefcase,
  FiCheckCircle,
  FiClipboard,
  FiCode,
  FiColumns,
  FiCompass,
  FiCpu,
  FiEye,
  FiFileText,
  FiGrid,
  FiHelpCircle,
  FiHome,
  FiLayout,
  FiLink,
  FiList,
  FiMessageCircle,
  FiMonitor,
  FiPackage,
  FiSettings,
  FiShield,
  FiUserPlus,
  FiUsers,
  FiX,
  FiZap,
} from "react-icons/fi";

export type IconKey = string;

const registry: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  home: FiHome,
  compass: FiCompass,
  dashboard: FiCompass,
  grid: FiGrid,
  users: FiUsers,
  "user-plus": FiUserPlus,
  monitor: FiMonitor,
  activity: FiActivity,
  "check-circle": FiCheckCircle,
  clipboard: FiClipboard,
  book: FiBook,
  "alert-circle": FiAlertCircle,
  package: FiPackage,
  zap: FiZap,
  "help-circle": FiHelpCircle,
  columns: FiColumns,
  cpu: FiCpu,
  "message-circle": FiMessageCircle,
  shield: FiShield,
  "file-text": FiFileText,
  "bar-chart": FiBarChart2,
  briefcase: FiBriefcase,
  link: FiLink,
  layout: FiLayout,
  list: FiList,
  eye: FiEye,
  settings: FiSettings,
  code: FiCode,
  bookmark: FiBookmark,
  box: FiBox,
  x: FiX,
};

export function getIcon(key: string): React.ComponentType<{ size?: number; className?: string }> {
  return registry[key] ?? FiBox;
}
