export type Role = 'admin' | 'dev' | 'company' | 'user' | 'support' | 'leader_tc' | 'technical_support';

export const ROLE_DEFAULTS: Record<Role, Record<string, string[]>> = {
  admin: {
    dashboard: ['view'],
    applications: ['view', 'create', 'edit', 'delete', 'export'],
    releases: ['view', 'create', 'edit', 'delete'],
    runs: ['view', 'create', 'edit', 'delete', 'export'],
    defects: ['view', 'create', 'edit', 'delete'],
    tickets: ['view', 'create', 'edit', 'delete', 'assign', 'status', 'comment', 'view_own', 'view_company', 'view_all'],
    support: ['view', 'create', 'assign', 'status', 'comment', 'modal', 'floating'],
    users: ['view', 'create', 'edit', 'delete', 'view_company', 'view_all'],
    permissions: ['view', 'edit', 'reset', 'clone'],
    access_requests: ['view'],
    notes: ['view', 'create', 'edit', 'delete'],
    notifications: ['view', 'create'],
    audit: ['view', 'export'],
    settings: ['view', 'edit'],
    ai: ['view', 'use'],
  },
  dev: {
    dashboard: ['view'],
    applications: ['view', 'create', 'edit', 'delete', 'export'],
    releases: ['view', 'create', 'edit', 'delete'],
    runs: ['view', 'create', 'edit', 'delete', 'export'],
    defects: ['view', 'create', 'edit', 'delete'],
    tickets: ['view', 'create', 'edit', 'delete', 'assign', 'status', 'comment', 'view_own', 'view_company', 'view_all'],
    support: ['view', 'create', 'assign', 'status', 'comment', 'modal', 'floating'],
    users: ['view', 'create', 'edit', 'delete', 'view_company', 'view_all'],
    permissions: ['view', 'edit', 'reset', 'clone'],
    access_requests: ['view', 'comment', 'approve', 'reject'],
    notes: ['view', 'create', 'edit', 'delete'],
    notifications: ['view', 'create'],
    audit: ['view', 'export'],
    settings: ['view', 'edit'],
    ai: ['view', 'use'],
  },
  company: {
    dashboard: ['view'],
    applications: ['view', 'create', 'edit'],
    releases: ['view'],
    runs: ['view'],
    defects: ['view'],
    tickets: ['view', 'create', 'comment', 'view_own'],
    support: ['view', 'create', 'comment', 'modal', 'floating'],
    users: [],
    permissions: [],
    access_requests: [],
    notes: ['view', 'create'],
    notifications: ['view'],
    audit: [],
    settings: ['view', 'edit'],
    ai: ['view', 'use'],
  },
  user: {
    dashboard: ['view'],
    applications: ['view'],
    releases: [],
    runs: [],
    defects: [],
    tickets: ['view', 'create', 'comment', 'view_own'],
    support: ['view', 'create', 'comment', 'modal', 'floating'],
    users: [],
    permissions: [],
    access_requests: [],
    notes: ['view', 'create'],
    notifications: ['view'],
    audit: [],
    settings: ['view', 'edit'],
    ai: ['view', 'use'],
  },
  support: {
    dashboard: ['view'],
    tickets: ['view', 'create', 'edit', 'assign', 'status', 'comment', 'view_company'],
    support: ['view', 'create', 'assign', 'status', 'comment', 'modal', 'floating'],
    users: ['view', 'view_company'],
    permissions: [],
    access_requests: [],
    notifications: ['view'],
    ai: ['view', 'use'],
  },
  leader_tc: {
    dashboard: ['view'],
    applications: ['view', 'create', 'edit'],
    releases: ['view'],
    runs: ['view'],
    defects: ['view'],
    tickets: ['view', 'create', 'comment', 'view_own'],
    support: ['view', 'create', 'comment', 'modal', 'floating'],
    users: ['view', 'create', 'edit'],
    permissions: [],
    access_requests: [],
    notes: ['view', 'create'],
    notifications: ['view'],
    audit: [],
    settings: ['view'],
    ai: ['view', 'use'],
  },
  technical_support: {
    dashboard: ['view'],
    tickets: ['view', 'create', 'edit', 'assign', 'status', 'comment', 'view_company'],
    support: ['view', 'create', 'assign', 'status', 'comment', 'modal', 'floating'],
    users: ['view', 'view_company'],
    permissions: [],
    access_requests: [],
    notifications: ['view'],
    ai: ['view', 'use'],
  },
};
