import { normalizeLegacyRole, SYSTEM_ROLES, type SystemRole } from "@/lib/auth/roles";

export type Role = SystemRole;

export const ROLE_DEFAULTS: Record<Role, Record<string, string[]>> = {
  [SYSTEM_ROLES.EMPRESA]: {
    dashboard: ["view"],
    context: ["view_own_company", "switch_project", "view_linked_projects"],
    applications: ["view", "create", "edit"],
    operations: [],
    release_calendar: [],
    releases: ["view"],
    runs: ["view"],
    defects: ["view"],
    documents: ["view", "create", "edit"],
    tickets: ["view", "create", "comment", "view_own"],
    support: ["view", "create", "comment", "modal", "floating"],
    users: ["view", "create"],
    permissions: [],
    access_requests: ["view", "comment", "approve", "reject"],
    notes: ["view", "create"],
    notifications: ["view"],
    audit: [],
    settings: ["view", "edit"],
    ai: ["view", "use"],
    brain: ["view", "graph", "ask", "read", "use"],
    chat: ["view", "use"],
    assistant: [],
    qase: [],
    jira: [],
    test_repository: ["read"],
    test_plan: ["read"],
    test_run: ["read"],
    playwright: ["read"],
    defect_tracking: ["read"],
    release_management: ["read"],
  },
  [SYSTEM_ROLES.COMPANY_USER]: {
    dashboard: ["view"],
    context: ["view_own_company", "switch_project", "view_linked_projects"],
    applications: ["view"],
    operations: [],
    release_calendar: [],
    releases: [],
    runs: [],
    defects: [],
    documents: ["view"],
    tickets: ["view", "create", "comment", "view_own"],
    support: ["view", "create", "comment", "modal", "floating"],
    users: ["view", "create"],
    permissions: [],
    access_requests: [],
    notes: ["view", "create"],
    notifications: ["view"],
    audit: [],
    settings: ["view", "edit"],
    ai: ["view", "use"],
    brain: ["view", "graph", "ask", "read", "use"],
    chat: ["view", "use"],
    assistant: [],
    qase: [],
    jira: [],
    test_repository: [],
    test_plan: [],
    test_run: [],
    playwright: [],
    defect_tracking: [],
    release_management: [],
  },
  [SYSTEM_ROLES.TESTING_COMPANY_USER]: {
    dashboard: ["view"],
    context: ["switch_company", "switch_project", "view_linked_companies", "view_linked_projects"],
    applications: ["view"],
    operations: [],
    release_calendar: [],
    releases: [],
    runs: [],
    defects: [],
    documents: ["view", "create"],
    tickets: ["view", "create", "comment", "view_own"],
    support: ["view", "create", "comment", "modal", "floating"],
    users: ["view", "create"],
    permissions: [],
    access_requests: [],
    notes: ["view", "create"],
    notifications: ["view"],
    audit: [],
    settings: ["view", "edit"],
    ai: ["view", "use"],
    brain: ["view", "graph", "ask", "read", "use", "view_external_sources", "use_qase_data"],
    chat: ["view", "use"],
    assistant: ["query_qase"],
    qase: ["view", "view_projects", "view_suites", "view_cases", "view_runs", "view_results", "view_defects"],
    jira: [],
    test_repository: ["read", "create", "update"],
    test_plan: ["read", "create", "update"],
    test_run: ["read", "create", "update"],
    playwright: ["read", "execute"],
    defect_tracking: ["read", "create", "update"],
    release_management: ["read"],
  },
  [SYSTEM_ROLES.LEADER_TC]: {
    dashboard: ["view"],
    context: ["global_overview", "view_all_companies", "view_all_projects"],
    applications: ["view", "create", "edit", "delete", "export"],
    operations: ["view"],
    release_calendar: ["view", "create", "edit", "status"],
    metrics: ["view", "export"],
    testPlans: ["view", "create", "edit", "delete"],
    releases: ["view", "create", "edit", "delete"],
    runs: ["view", "create", "edit", "delete", "export"],
    defects: ["view", "create", "edit", "delete"],
    documents: ["view", "create", "edit", "delete"],
    tickets: ["view", "create", "edit", "delete", "assign", "status", "comment", "view_own", "view_company", "view_all"],
    support: ["view", "create", "assign", "status", "comment", "modal", "floating"],
    users: ["view", "create", "edit", "delete", "view_company", "view_all"],
    permissions: ["view", "edit", "reset", "clone"],
    access_requests: ["view", "comment", "approve", "reject"],
    notes: ["view", "create", "edit", "delete"],
    notifications: ["view", "create"],
    audit: ["view", "export"],
    settings: ["view", "edit"],
    ai: ["view", "use"],
    brain: ["view", "graph", "ask", "admin", "read", "use", "view_external_sources", "use_qase_data", "use_jira_data"],
    chat: ["view", "use"],
    assistant: ["query_qase", "query_jira", "create_external_ticket", "update_external_ticket"],
    qase: ["view", "view_projects", "view_suites", "view_cases", "view_runs", "view_results", "view_defects", "create_case", "update_case", "create_run", "update_run", "sync", "link_defect"],
    jira: ["view", "view_projects", "view_issues", "view_bugs", "view_epics", "view_sprints", "create_issue", "update_issue", "transition_issue", "comment_issue", "link_issue", "sync"],
    test_repository: ["read", "create", "update", "delete", "import"],
    test_plan: ["read", "create", "update", "delete"],
    test_run: ["read", "create", "update", "delete"],
    playwright: ["read", "execute"],
    defect_tracking: ["read", "create", "update", "delete", "assign", "status"],
    release_management: ["read", "create", "approve", "block"],
  },
  [SYSTEM_ROLES.TECHNICAL_SUPPORT]: {
    dashboard: ["view"],
    context: ["global_overview", "view_all_companies", "view_all_projects"],
    applications: ["view", "create", "edit"],
    operations: ["view"],
    release_calendar: ["view", "create", "edit", "status"],
    releases: ["view"],
    runs: ["view"],
    defects: ["view"],
    documents: ["view"],
    tickets: ["view", "create", "edit", "assign", "status", "comment", "view_all"],
    support: ["view", "create", "assign", "status", "comment", "modal", "floating"],
    users: ["view"],
    permissions: ["view"],
    access_requests: ["view", "comment", "approve", "reject"],
    notes: ["view", "create"],
    notifications: ["view"],
    audit: ["view"],
    settings: ["view"],
    ai: ["view", "use"],
    brain: ["view", "graph", "ask", "admin", "read", "use", "view_external_sources", "use_qase_data", "use_jira_data"],
    chat: ["view", "use"],
    assistant: ["query_qase", "query_jira"],
    qase: ["view", "view_projects", "view_suites", "view_cases", "view_runs", "view_results", "view_defects"],
    jira: ["view", "view_projects", "view_issues", "view_bugs", "view_epics", "view_sprints"],
    test_repository: ["read", "create", "update"],
    test_plan: ["read"],
    test_run: ["read"],
    playwright: ["read", "execute"],
    defect_tracking: ["read", "create", "update", "assign", "status"],
    release_management: ["read"],
  },
};

export function resolveRoleDefaults(role?: string | null) {
  const normalizedRole = normalizeLegacyRole(role);
  return normalizedRole ? ROLE_DEFAULTS[normalizedRole] : {};
}
