import { normalizeLegacyRole, SYSTEM_ROLES, type SystemRole } from "@/lib/auth/roles";

export type Role = SystemRole;

export const ROLE_DEFAULTS: Record<Role, Record<string, string[]>> = {
  [SYSTEM_ROLES.EMPRESA]: {
    dashboard: ["view"],
    applications: ["view", "create", "edit"],
    releases: ["view"],
    runs: ["view"],
    defects: ["view"],
    tickets: ["view", "create", "comment", "view_own"],
    support: ["view", "create", "comment", "modal", "floating"],
    users: [],
    permissions: [],
    access_requests: [],
    notes: ["view", "create"],
    notifications: ["view"],
    audit: [],
    settings: ["view", "edit"],
    ai: ["view", "use"],
  },
  [SYSTEM_ROLES.COMPANY_USER]: {
    dashboard: ["view"],
    applications: ["view"],
    releases: [],
    runs: [],
    defects: [],
    tickets: ["view", "create", "comment", "view_own"],
    support: ["view", "create", "comment", "modal", "floating"],
    users: [],
    permissions: [],
    access_requests: [],
    notes: ["view", "create"],
    notifications: ["view"],
    audit: [],
    settings: ["view", "edit"],
    ai: ["view", "use"],
  },
  [SYSTEM_ROLES.TESTING_COMPANY_USER]: {
    dashboard: ["view"],
    applications: ["view"],
    releases: [],
    runs: [],
    defects: [],
    tickets: ["view", "create", "comment", "view_own"],
    support: ["view", "create", "comment", "modal", "floating"],
    users: [],
    permissions: [],
    access_requests: [],
    notes: ["view", "create"],
    notifications: ["view"],
    audit: [],
    settings: ["view", "edit"],
    ai: ["view", "use"],
  },
  [SYSTEM_ROLES.LEADER_TC]: {
    dashboard: ["view"],
    applications: ["view", "create", "edit"],
    releases: ["view"],
    runs: ["view"],
    defects: ["view"],
    tickets: ["view", "create", "comment", "view_own"],
    support: ["view", "create", "comment", "modal", "floating"],
    users: ["view", "create", "edit"],
    permissions: ["view", "edit", "reset", "clone"],
    access_requests: ["view", "comment", "approve", "reject"],
    notes: ["view", "create"],
    notifications: ["view"],
    audit: [],
    settings: ["view"],
    ai: ["view", "use"],
  },
  [SYSTEM_ROLES.TECHNICAL_SUPPORT]: {
    dashboard: ["view"],
    applications: ["view", "create", "edit"],
    releases: ["view"],
    runs: ["view"],
    defects: ["view"],
    tickets: ["view", "create", "edit", "assign", "status", "comment", "view_all"],
    support: ["view", "create", "assign", "status", "comment", "modal", "floating"],
    users: ["view"],
    permissions: ["view"],
    access_requests: ["view"],
    notes: ["view", "create"],
    notifications: ["view"],
    audit: ["view"],
    settings: ["view"],
    ai: ["view", "use"],
  },
};

export function resolveRoleDefaults(role?: string | null) {
  const normalizedRole = normalizeLegacyRole(role);
  return normalizedRole ? ROLE_DEFAULTS[normalizedRole] : {};
}
