export const JOB_TITLE_DATALIST_ID = "job-title-options";

export const JOB_TITLE_OPTIONS = [
  "Analista de QA",
  "Analista de Testes",
  "Analista de Automação",
  "Analista de Suporte",
  "Analista de Sistemas",
  "Analista de Negócios",
  "Analista de Dados",
  "Analista de Produto",
  "Assistente Administrativo",
  "Assistente de Suporte",
  "Coordenador de QA",
  "Coordenador de Suporte",
  "Coordenador de Projetos",
  "Consultor",
  "Consultor de Implantação",
  "Customer Success",
  "Desenvolvedor Back-end",
  "Desenvolvedor Front-end",
  "Desenvolvedor Full Stack",
  "Desenvolvedor Mobile",
  "Designer UX/UI",
  "DevOps",
  "Diretor",
  "Engenheiro de Dados",
  "Engenheiro de Qualidade",
  "Engenheiro de Software",
  "Especialista de Produto",
  "Especialista de Suporte",
  "Gerente",
  "Gerente de Contas",
  "Gerente de Produto",
  "Gerente de Projetos",
  "Gerente de QA",
  "Gerente de Suporte",
  "Líder Técnico",
  "PO",
  "Product Manager",
  "QA Lead",
  "Scrum Master",
  "Suporte Técnico",
  "Tech Lead",
  "Testador",
  "Tester",
];
