export const JOB_TITLE_OPTIONS = [
  "Advogado",
  "Analista Administrativo",
  "Analista Comercial",
  "Analista Contabil",
  "Analista de Atendimento",
  "Analista de Automacao",
  "Analista de BI",
  "Analista de Compras",
  "Analista de Compliance",
  "Analista de Dados",
  "Analista de DevOps",
  "Analista de Implantacao",
  "Analista de Infraestrutura",
  "Analista de Marketing",
  "Analista de Negocios",
  "Analista de Processos",
  "Analista de Produto",
  "Analista de Projetos",
  "Analista de QA",
  "Analista de RH",
  "Analista de Requisitos",
  "Analista de Seguranca da Informacao",
  "Analista de Sistemas",
  "Analista de Sucesso do Cliente",
  "Analista de Suporte",
  "Analista de Testes",
  "Analista Financeiro",
  "Arquiteto de Software",
  "Assistente Administrativo",
  "Assistente Comercial",
  "Assistente de Atendimento",
  "Assistente de Marketing",
  "Assistente de RH",
  "Assistente de Suporte",
  "Auxiliar Administrativo",
  "Business Analyst",
  "CEO",
  "CFO",
  "COO",
  "Cientista de Dados",
  "Consultor",
  "Consultor Comercial",
  "Consultor de Implantacao",
  "Consultor de Negocios",
  "Consultor de Sistemas",
  "Consultor SAP",
  "Coordenador",
  "Coordenador Administrativo",
  "Coordenador Comercial",
  "Coordenador de Atendimento",
  "Coordenador de Operacoes",
  "Coordenador de Produto",
  "Coordenador de Projetos",
  "Coordenador de QA",
  "Coordenador de RH",
  "Coordenador de Suporte",
  "Copywriter",
  "Customer Experience",
  "Customer Success",
  "DBA",
  "Desenvolvedor Android",
  "Desenvolvedor Back-end",
  "Desenvolvedor Front-end",
  "Desenvolvedor Full Stack",
  "Desenvolvedor iOS",
  "Desenvolvedor Mobile",
  "Designer UX",
  "Designer UX/UI",
  "Designer Visual",
  "Designer de Produto",
  "Designer Grafico",
  "DevOps",
  "Diretor",
  "Diretor Comercial",
  "Diretor de Operacoes",
  "Diretor de Produto",
  "Diretor de Tecnologia",
  "Editor de Conteudo",
  "Engenheiro Cloud",
  "Engenheiro DevOps",
  "Engenheiro de Dados",
  "Engenheiro de Machine Learning",
  "Engenheiro de Plataforma",
  "Engenheiro de Qualidade",
  "Engenheiro de Software",
  "Engenheiro de Testes",
  "Especialista de Implantacao",
  "Especialista de Produto",
  "Especialista de Processos",
  "Especialista de Suporte",
  "Especialista em Automacao",
  "Especialista em Dados",
  "Especialista em Seguranca",
  "Especialista em Testes",
  "Gerente",
  "Gerente Comercial",
  "Gerente de Atendimento",
  "Gerente de Contas",
  "Gerente de Customer Success",
  "Gerente de Marketing",
  "Gerente de Operacoes",
  "Gerente de Produto",
  "Gerente de Projetos",
  "Gerente de QA",
  "Gerente de RH",
  "Gerente de Suporte",
  "Head de Produto",
  "Head de Tecnologia",
  "Lider Tecnico",
  "PO",
  "PMO",
  "Product Designer",
  "Product Manager",
  "Product Owner",
  "Programador",
  "QA",
  "QA Analyst",
  "QA Lead",
  "QA Manager",
  "Recepcionista",
  "Scrum Master",
  "Social Media",
  "Software Engineer",
  "Suporte Tecnico",
  "Supervisor",
  "Supervisor Comercial",
  "Supervisor de Atendimento",
  "Supervisor de Operacoes",
  "Team Lead",
  "Tech Lead",
  "Tecnico de Informatica",
  "Tecnico de Suporte",
  "Test Automation Engineer",
  "Testador",
  "Tester",
  "UX Researcher",
  "UX Writer",
  "Vendedor",
] as const;
