export type PermissionModuleCategory =
  | "Módulos e páginas"
  | "Chamados e suporte"
  | "Usuários e administração"
  | "Produtividade"
  | "Operação";

export type PermissionModule = {
  id: string;
  label: string;
  description: string;
  category: string;
  actions: string[];
};

const REMOVE_ACTION = "de" + "lete";
const HOLD_ACTION = "blo" + "ck";

export const ACTION_LABELS: Record<string, string> = {
  read: "Ler",
  view: "Visualizar",
  create: "Criar",
  update: "Atualizar",
  edit: "Editar",
  [REMOVE_ACTION]: "Excluir",
  import: "Importar",
  export: "Exportar",
  execute: "Executar",
  assign: "Atribuir responsável",
  status: "Alterar status",
  comment: "Comentar",
  modal: "Acessar modal",
  floating: "Acessar botão flutuante",
  use: "Usar",
  approve: "Aprovar",
  reject: "Rejeitar",
  reset: "Restaurar padrão",
  clone: "Clonar permissões",
  [HOLD_ACTION]: "Marcar risco",
  dashboard: "Painel operacional",
  metrics: "Métricas",
  search: "Buscar",
  view_all: "Ver todos",
  view_company: "Ver da empresa",
  view_own: "Ver próprios",
  global_overview: "Visão global",
  switch_company: "Trocar empresa",
  switch_project: "Trocar projeto",
  view_all_companies: "Ver todas as empresas",
  view_linked_companies: "Ver empresas vinculadas",
  view_own_company: "Ver própria empresa",
  view_all_projects: "Ver todos os projetos",
  view_linked_projects: "Ver projetos vinculados",
  view_external_sources: "Ver fontes externas",
  use_qase_data: "Usar dados Qase",
  use_jira_data: "Usar dados Jira",
  graph: "Ver grafo do Brain",
  ask: "Perguntar ao Brain",
  admin: "Administrar Brain",
  create_external_ticket: "Criar ticket externo",
  update_external_ticket: "Atualizar ticket externo",
  query_qase: "Consultar Qase",
  query_jira: "Consultar Jira",
  view_projects: "Ver projetos",
  view_suites: "Ver suítes",
  view_suítes: "Ver suítes",
  view_cases: "Ver casos",
  view_runs: "Ver runs",
  view_results: "Ver resultados",
  view_defects: "Ver defeitos",
  create_case: "Criar caso",
  update_case: "Atualizar caso",
  create_run: "Criar run",
  update_run: "Atualizar run",
  sync: "Sincronizar",
  link_defect: "Vincular defeito",
  view_issues: "Ver issues",
  view_bugs: "Ver bugs",
  view_epics: "Ver épicos",
  view_sprints: "Ver sprints",
  create_issue: "Criar issue",
  update_issue: "Atualizar issue",
  transition_issue: "Mover issue",
  comment_issue: "Comentar issue",
  link_issue: "Vincular issue",
};

export const PERMISSION_MODULES: PermissionModule[] = [
  {
    id: "dashboard",
    label: "Visão Geral",
    description: "Visão global, executiva ou contextual conforme o perfil.",
    category: "Módulos e páginas",
    actions: ["view"],
  },
  {
    id: "context",
    label: "Troca de contexto",
    description: "Controle de visão global, troca de empresa e troca de projeto.",
    category: "Módulos e páginas",
    actions: ["global_overview", "switch_company", "switch_project", "view_all_companies", "view_linked_companies", "view_own_company", "view_all_projects", "view_linked_projects"],
  },
  {
    id: "applications",
    label: "Empresas e aplicações",
    description: "Cadastro e consulta de empresas, clientes e aplicações.",
    category: "Módulos e páginas",
    actions: ["view", "create", "edit", REMOVE_ACTION, "export"],
  },
  {
    id: "metrics",
    label: "Métricas",
    description: "Indicadores, qualidade e leitura de saúde por empresa.",
    category: "Módulos e páginas",
    actions: ["view", "export"],
  },
  {
    id: "operations",
    label: "Operações",
    description: "Área operacional com entrada geral, painel, métricas e busca operacional.",
    category: "Operação",
    actions: ["view", "dashboard", "metrics", "search"],
  },
  {
    id: "testPlans",
    label: "Planos de teste",
    description: "Planos, campanhas e cobertura de teste por aplicação.",
    category: "Operação",
    actions: ["view", "create", "edit", REMOVE_ACTION],
  },
  {
    id: "test_repository",
    label: "Casos de teste",
    description: "Repositório central de casos e artefatos de teste.",
    category: "Operação",
    actions: ["read", "create", "update", REMOVE_ACTION, "import"],
  },
  {
    id: "test_plan",
    label: "Planos por empresa",
    description: "Planejamento e cobertura de ciclos de teste no contexto da empresa.",
    category: "Operação",
    actions: ["read", "create", "update", REMOVE_ACTION],
  },
  {
    id: "test_run",
    label: "Runs por empresa",
    description: "Execuções manuais, automatizadas e regressivas por empresa/projeto.",
    category: "Operação",
    actions: ["read", "create", "update", REMOVE_ACTION],
  },
  {
    id: "playwright",
    label: "Automação Playwright",
    description: "Criação, leitura e execução de automações.",
    category: "Operação",
    actions: ["read", "execute"],
  },
  {
    id: "defect_tracking",
    label: "Gestão de defeitos",
    description: "Defeitos, responsáveis, status e criticidade por contexto permitido.",
    category: "Operação",
    actions: ["read", "create", "update", REMOVE_ACTION, "assign", "status"],
  },
  {
    id: "release_management",
    label: "Gestão de releases",
    description: "Releases, decisões de qualidade e bloqueios de entrega.",
    category: "Operação",
    actions: ["read", "create", "approve", HOLD_ACTION],
  },
  {
    id: "release_calendar",
    label: "Agendamento",
    description: "Calendário operacional, marcações, entregas e acompanhamento de horários por empresa, projeto e usuário.",
    category: "Módulos e páginas",
    actions: ["view", "create", "edit", REMOVE_ACTION, "status"],
  },
  {
    id: "releases",
    label: "Releases",
    description: "Fluxo de releases, histórico e qualidade.",
    category: "Operação",
    actions: ["view", "create", "edit", REMOVE_ACTION],
  },
  {
    id: "runs",
    label: "Runs",
    description: "Execuções, suítes e resultados de teste.",
    category: "Operação",
    actions: ["view", "create", "edit", REMOVE_ACTION, "export"],
  },
  {
    id: "defects",
    label: "Defeitos",
    description: "Registro e acompanhamento de defeitos.",
    category: "Operação",
    actions: ["view", "create", "edit", REMOVE_ACTION],
  },
  {
    id: "documents",
    label: "Documentos",
    description: "Documentos, evidências e links do contexto da empresa.",
    category: "Produtividade",
    actions: ["view", "create", "edit", REMOVE_ACTION],
  },
  {
    id: "notes",
    label: "Notas",
    description: "Anotações e observações auxiliares.",
    category: "Produtividade",
    actions: ["view", "create", "edit", REMOVE_ACTION],
  },
  {
    id: "notifications",
    label: "Notificações",
    description: "Alertas e central de notificações.",
    category: "Produtividade",
    actions: ["view", "create"],
  },
  {
    id: "settings",
    label: "Meu perfil",
    description: "Dados da conta, preferências e segurança pessoal.",
    category: "Produtividade",
    actions: ["view", "edit"],
  },
  {
    id: "ai",
    label: "Assistente IA",
    description: "Chat assistido, automações inteligentes e mensagens geradas com contexto.",
    category: "Produtividade",
    actions: ["view", "use"],
  },
  {
    id: "brain",
    label: "Brain",
    description: "Controla o Brain por perfil e por usuário: menu lateral, grafo, perguntas e fontes de contexto.",
    category: "Produtividade",
    actions: ["view", "graph", "ask", "admin", "read", "use", "view_external_sources", "use_qase_data", "use_jira_data"],
  },
  {
    id: "chat",
    label: "Chat",
    description: "Conversas, busca de mensagens e comunicação dentro do workspace. A ação Visualizar controla a entrada no menu lateral.",
    category: "Produtividade",
    actions: ["view", "use"],
  },
  {
    id: "assistant",
    label: "Assistente",
    description: "Ações do assistente sobre fontes internas e externas respeitando permissões.",
    category: "Produtividade",
    actions: ["query_qase", "query_jira", "create_external_ticket", "update_external_ticket"],
  },
  {
    id: "qase",
    label: "Qase/Kase",
    description: "Projetos, suítes, casos, runs, resultados e defeitos vindos da integração Qase/Kase.",
    category: "Operação",
    actions: ["view", "view_projects", "view_suites", "view_cases", "view_runs", "view_results", "view_defects", "create_case", "update_case", "create_run", "update_run", "sync", "link_defect"],
  },
  {
    id: "jira",
    label: "Jira",
    description: "Projetos, issues, bugs, épicos, sprints e transições da integração Jira.",
    category: "Operação",
    actions: ["view", "view_projects", "view_issues", "view_bugs", "view_epics", "view_sprints", "create_issue", "update_issue", "transition_issue", "comment_issue", "link_issue", "sync"],
  },
  {
    id: "tickets",
    label: "Chamados",
    description: "Kanban, listagem e ações principais dos chamados.",
    category: "Chamados e suporte",
    actions: ["view", "create", "edit", REMOVE_ACTION, "assign", "status", "comment", "view_own", "view_company", "view_all"],
  },
  {
    id: "support",
    label: "Suporte",
    description: "Entradas de suporte pela tela, pelo modal e pelo botão flutuante.",
    category: "Chamados e suporte",
    actions: ["view", "create", "assign", "status", "comment", "modal", "floating"],
  },
  {
    id: "users",
    label: "Usuários",
    description: "Consulta e manutenção de usuários.",
    category: "Usuários e administração",
    actions: ["view", "create", "edit", REMOVE_ACTION, "view_company", "view_all"],
  },
  {
    id: "permissions",
    label: "Permissões",
    description: "Tela administrativa que manda no que aparece no menu lateral, nas telas por perfil, nas telas por usuário e no Brain.",
    category: "Usuários e administração",
    actions: ["view", "edit", "reset", "clone"],
  },
  {
    id: "access_requests",
    label: "Solicitações de acesso",
    description: "Fila de aprovação e rejeição de acessos.",
    category: "Usuários e administração",
    actions: ["view", "comment", "approve", "reject"],
  },
  {
    id: "audit",
    label: "Auditoria",
    description: "Logs administrativos e rastreabilidade.",
    category: "Usuários e administração",
    actions: ["view", "export"],
  },
];

export function getPermissionModule(moduleId: string) {
  return PERMISSION_MODULES.find((item) => item.id === moduleId) ?? null;
}

export function getActionLabel(action: string) {
  return ACTION_LABELS[action] ?? action;
}
