-- Manual Kanban (DB)
-- Creates a DB-backed store for manual Kanban cards and basic RLS.

create table if not exists public.kanban_cards (
  id bigint generated by default as identity primary key,
  client_slug text not null,
  project text not null,
  run_id integer not null,
  case_id integer null,
  title text not null,
  status text not null,
  bug text null,
  link text null,
  created_at timestamptz not null default now(),
  created_by uuid null
);

create index if not exists kanban_cards_client_project_run_idx
  on public.kanban_cards (client_slug, project, run_id);

alter table public.kanban_cards enable row level security;

-- Global admin policy helper: profile.is_global_admin
-- Company policy helper: users.cliente matches card.client_slug

drop policy if exists "kanban_cards_select" on public.kanban_cards;
drop policy if exists "kanban_cards_insert" on public.kanban_cards;
drop policy if exists "kanban_cards_update" on public.kanban_cards;
drop policy if exists "kanban_cards_delete" on public.kanban_cards;

create policy "kanban_cards_select"
  on public.kanban_cards
  for select
  to authenticated
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_global_admin = true)
    or exists (select 1 from public.users u where u.id = auth.uid() and u.cliente = kanban_cards.client_slug)
  );

create policy "kanban_cards_insert"
  on public.kanban_cards
  for insert
  to authenticated
  with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_global_admin = true)
    or exists (select 1 from public.users u where u.id = auth.uid() and u.cliente = kanban_cards.client_slug)
  );

create policy "kanban_cards_update"
  on public.kanban_cards
  for update
  to authenticated
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_global_admin = true)
    or exists (select 1 from public.users u where u.id = auth.uid() and u.cliente = kanban_cards.client_slug)
  )
  with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_global_admin = true)
    or exists (select 1 from public.users u where u.id = auth.uid() and u.cliente = kanban_cards.client_slug)
  );

create policy "kanban_cards_delete"
  on public.kanban_cards
  for delete
  to authenticated
  using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_global_admin = true)
    or exists (select 1 from public.users u where u.id = auth.uid() and u.cliente = kanban_cards.client_slug)
  );
