import { NAV_CATALOG } from "@/lib/navigation/navigationCatalog";
import type { BrainContextCompany, BrainContextProject, BrainEdge, BrainNode, BrainNodeStatus } from "../_types/brain.types";

export type BrainViewerMode = "leadership" | "tc_user" | "company_user" | "company" | "unknown";
export type BrainProfileGraphOptions = { nodes: BrainNode[]; edges: BrainEdge[]; selectedNode: BrainNode | null; selectedProfileType: string | null; activeModule: string | null; companies: BrainContextCompany[]; projects: BrainContextProject[]; selectedCompanyId: string | null; selectedProjectId: string | null; canSeeAllCompanies: boolean; hasActiveFilter: boolean; viewerMode?: BrainViewerMode; viewerEmail?: string | null };
type Item = { id: string; routeId?: string; label: string; module?: string; href?: string; allowedRoles?: string[]; onlyRoles?: string[]; requiredPermission?: { moduleId: string; action: string }; children?: Item[] };
type Mod = Item & { items?: Item[] };
type ModView = { id: string; label: string; href?: string; requiredPermission?: { moduleId: string; action: string }; items: Array<{ module: ModView; item: Item }> };

const CORE_ID = "quality-control-core";
const PROFILES = ["Líder TC", "Suporte técnico", "Usuário Test Company", "Usuário empresarial", "Empresas"];
const USER_TYPES = ["Líder TC", "Suporte técnico", "Usuário Test Company", "Usuário empresarial"];
const PENDING = ["pending", "missing", "warning", "error", "orphan"];
const COLORS = ["#67e8f9", "#a78bfa", "#34d399", "#facc15", "#fb7185", "#60a5fa", "#f472b6", "#2dd4bf"];
const LEADER_MODULES = ["home", "agenda", "overview", "companies", "requests", "support", "chat", "brain", "logs", "management"];
const LEADER_ITEMS = ["companies-search", "companies-create", "requests-list", "support-create", "support-kanban", "brain-graph", "management-permissions", "management-profile", "management-users", "management-users-list", "management-users-create-tc", "management-users-create-company", "management-users-create-leader", "management-users-create-support"];
const ORDER = ["Home", "Agenda", "Visão Geral", "Gestão de Empresas", "Solicitações", "Suporte", "Chat", "Brain", "Logs", "Gestão"];

function n(v: unknown) { return String(v ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim(); }
function id(prefix: string, value: unknown) { return `${prefix}:${n(value).replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "sem-contexto"}`; }
function uniq<T extends { id: string }>(items: T[]) { return Array.from(new Map(items.map((item) => [item.id, item])).values()); }
function profileLabel(value: unknown) { const x = n(value); if (["leader", "lider", "leader_tc", "lider tc"].some((k) => x.includes(k))) return "Líder TC"; if (["technical", "suporte", "support"].some((k) => x.includes(k))) return "Suporte técnico"; if (["testing_company_user", "usuario tc", "tc user", "test company"].some((k) => x.includes(k))) return "Usuário Test Company"; if (["company_user", "usuario empresarial", "usuario empresa", "user company"].some((k) => x.includes(k))) return "Usuário empresarial"; if (["empresa", "company", "empresas"].some((k) => x === k || x.includes(k))) return "Empresas"; return String(value || "Usuário empresarial").trim(); }
function leader(profile: string | null) { const p = profileLabel(profile); return p === "Líder TC" || p === "Suporte técnico"; }
function companyProfile(profile: string | null) { const p = profileLabel(profile); return p === "Empresas" || p === "Usuário empresarial"; }
function roles(profile: string | null) { const p = profileLabel(profile); if (p === "Líder TC") return ["leader_tc"]; if (p === "Suporte técnico") return ["technical_support"]; if (p === "Usuário Test Company") return ["testing_company_user"]; if (p === "Empresas") return ["empresa", "company_user"]; return ["company_user"]; }
function roleAllowed(allowed: unknown, profile: string | null) { if (!Array.isArray(allowed) || !allowed.length) return true; const set = new Set(roles(profile).map(n)); return allowed.map(n).some((r) => set.has(r)); }
function itemAllowed(item: Item | Mod, profile: string | null) { if (Array.isArray(item.onlyRoles) && item.onlyRoles.length && !roleAllowed(item.onlyRoles, profile)) return false; return roleAllowed(item.allowedRoles, profile); }
function labelItem(item: Item) { if (item.id === "brain-graph") return "Brain visual"; if (item.id === "management-permissions") return "Gestão de permissões"; return item.label; }
function modLabel(module: string) { const x = n(module); const found = (NAV_CATALOG as Mod[]).find((m) => n(m.id) === x || n(m.label) === x); if (found) return found.label; return ({ quality: "Controle de qualidade", support: "Suporte", requests: "Solicitações", companies: "Gestão de Empresas", management: "Gestão", agenda: "Agenda", brain: "Brain", chat: "Chat", logs: "Logs", permissions: "Gestão de permissões", permissoes: "Gestão de permissões" } as Record<string, string>)[x] ?? module; }
function modOrder(module: string) { const i = ORDER.findIndex((x) => n(x) === n(modLabel(module))); return i < 0 ? 999 : i; }
function catalog(profile: string | null): ModView[] { return (NAV_CATALOG as Mod[]).filter((m) => leader(profile) ? LEADER_MODULES.includes(m.id) : itemAllowed(m, profile)).map((m) => { const view: ModView = { id: m.id, label: m.label, href: m.href, requiredPermission: m.requiredPermission, items: [] }; const visit = (it: Item) => { if (leader(profile)) { if (LEADER_ITEMS.includes(it.id)) view.items.push({ module: view, item: { ...it, label: labelItem(it) } }); } else if (itemAllowed(it, profile)) view.items.push({ module: view, item: { ...it, label: labelItem(it) } }); it.children?.forEach(visit); }; m.items?.forEach(visit); return view; }).sort((a, b) => modOrder(a.label) - modOrder(b.label)); }
function screens(profile: string | null, moduleName: string | null) { if (!moduleName) return []; const key = n(modLabel(moduleName)); return catalog(profile).filter((m) => n(m.label) === key || n(m.id) === n(moduleName)).flatMap((m) => [...(m.href ? [{ module: m, item: { id: `${m.id}-root`, routeId: m.id, label: m.label, module: m.id, href: m.href, requiredPermission: m.requiredPermission } as Item }] : []), ...m.items]); }
function status(nodes: BrainNode[]): BrainNodeStatus { return nodes.some((x) => PENDING.includes(x.status)) ? "pending" : "ok"; }
function pend(nodes: BrainNode[]) { return nodes.filter((x) => PENDING.includes(x.status)).length; }
function companyKey(node: BrainNode) { const m = node.metadata ?? {}; return (node.companyId ?? String(m.companyId ?? m.companySlug ?? m.company ?? node.companyName ?? "").trim()) || null; }
function companyName(node: BrainNode) { const m = node.metadata ?? {}; return (node.companyName ?? String(m.companyName ?? m.company ?? m.companySlug ?? "").trim()) || null; }
function color(key: string | null) { if (!key) return COLORS[0]; return COLORS[Array.from(key).reduce((s, c) => s + c.charCodeAt(0), 0) % COLORS.length]; }
function userType(node?: BrainNode | null) { const m = node?.metadata ?? {}; return profileLabel(m.userType ?? m.profileType ?? m.accessType ?? m.permissionRole ?? m.companyRole ?? m.role ?? m.requestedRole ?? (node?.type === "profile" ? node.label : null)); }
function creator(node: BrainNode) { const m = node.metadata ?? {}; return (node.createdByEmail ?? node.createdBy ?? String(m.userEmail ?? m.requesterEmail ?? m.email ?? m.createdBy ?? m.actorEmail ?? "").trim()) || null; }
function userName(node: BrainNode) { const m = node.metadata ?? {}; return String(m.userName ?? m.actorName ?? m.name ?? node.createdByEmail ?? node.createdBy ?? m.email ?? node.label ?? "Usuário do contexto").trim(); }
function withColor(node: BrainNode): BrainNode { const key = companyKey(node); return { ...node, metadata: { ...node.metadata, companyColor: color(key), companyKey: key, userType: userType(node) } }; }
function matches(node: BrainNode, profile: string, companyId: string | null, projectId: string | null, module: string | null) { if (profile && !node.metadata?.isPermissionNode && node.metadata?.accessType && n(profileTypeForNode(node)) !== n(profile)) return false; if (companyId && node.companyId && node.companyId !== companyId) return false; if (projectId && node.projectId && node.projectId !== projectId) return false; if (module && modLabel(node.module) !== modLabel(module)) return false; return true; }
export function profileTypeForNode(node: BrainNode) { const m = node.metadata ?? {}; return profileLabel(m.profileType ?? m.accessType ?? m.permissionRole ?? m.companyRole ?? m.role ?? m.requestedRole ?? (node.type === "profile" ? node.label : null)); }
export function getBrainProfileTypes(nodes: BrainNode[]) { return uniq([...PROFILES, ...nodes.map(profileTypeForNode)].map((label) => ({ id: n(label), label }))).map((x) => x.label); }
function groupUsers(nodes: BrainNode[]) { const map = new Map<string, BrainNode[]>(); nodes.forEach((node) => { const key = creator(node); if (key) map.set(key, [...(map.get(key) ?? []), node]); }); return map; }
function nodeBase(idValue: string, type: BrainNode["type"], module: string, label: string, nodes: BrainNode[], meta: Record<string, unknown>): BrainNode { return { id: idValue, type, module, label, status: status(nodes), size: "lg", information: `${label}: ${nodes.length} item(ns).`, metadata: { ...meta, count: nodes.length, pendingCount: pend(nodes) } }; }
function screenNode(profile: string, row: ReturnType<typeof screens>[number]): BrainNode { const req = row.item.requiredPermission; return { id: id(`permission:${profile}:${row.module.id}`, row.item.routeId ?? row.item.id), type: "permission", module: row.module.label, label: row.item.label, description: `Tela liberada para ${profile}.`, status: "ok", size: "md", information: req ? `${row.item.label} depende de ${req.moduleId}:${req.action}.` : `${row.item.label} é acesso padrão de ${profile}.`, requiredPermissions: req ? [`${req.moduleId}:${req.action}`] : [], visibleByPermission: true, source: { type: "navigation", route: row.item.href }, metadata: { isPermissionNode: true, isDetailNode: true, profileType: profile, layer: 5, layerLabel: "5. Tela liberada", routeId: row.item.routeId, route: row.item.href, requiredPermission: req ? `${req.moduleId}:${req.action}` : "perfil" } }; }

export function buildBrainProfileGraphView(options: BrainProfileGraphOptions) {
  const { nodes, edges, selectedNode, selectedProfileType, activeModule, companies, projects, selectedCompanyId, selectedProjectId, canSeeAllCompanies, hasActiveFilter, viewerMode = "unknown", viewerEmail = null } = options;
  const mode = viewerMode === "unknown" ? (canSeeAllCompanies ? "leadership" : "company_user") : viewerMode;
  const fromNode = selectedNode?.metadata?.isProfileRoot ? String(selectedNode.metadata.profileType ?? selectedNode.label) : null;
  const profile = selectedProfileType ?? fromNode ?? (mode === "company_user" || mode === "company" ? "Empresas" : "Líder TC");
  const company = companies.find((c) => c.id === selectedCompanyId) ?? null;
  const moduleFocus = activeModule ?? (selectedNode?.metadata?.isModuleHub ? String(selectedNode.metadata.moduleLabel ?? selectedNode.label) : null);
  const base = nodes.filter((node) => matches(node, profile, selectedCompanyId, selectedProjectId, activeModule)).map(withColor).filter((node) => (mode === "tc_user" || mode === "company_user") ? (!viewerEmail || !creator(node) || creator(node) === viewerEmail) : true);
  const graphNodes: BrainNode[] = [];
  const graphEdges: BrainEdge[] = [];
  const core = nodeBase(CORE_ID, "module", "Núcleo", "Quality Control", nodes, { isBrainCore: true, isContextCore: true, layer: 0, layerLabel: "0. Núcleo", profileFlow: PROFILES });
  const profileNode = nodeBase(id("profile", profile), "profile", "1. Perfil", profile, base, { isProfileRoot: true, profileType: profile, layer: 1, layerLabel: "1. Perfil", permissionModules: catalog(profile).map((m) => m.label) });
  graphNodes.push(core, profileNode);
  graphEdges.push({ id: `${core.id}-${profileNode.id}`, source: core.id, target: profileNode.id, label: "perfil", type: "relation", status: profileNode.status });
  const scopes = [nodeBase(id(`scope:${profile}`, "companies"), "module", "Gestão", "Empresas", base, { isScopeHub: true, scopeType: "companies", profileType: profile, layer: 2, layerLabel: "2. Empresas" }), nodeBase(id(`scope:${profile}`, "users"), "module", "Gestão", "Usuários por perfil", base.filter(creator), { isScopeHub: true, scopeType: "users", profileType: profile, layer: 2, layerLabel: "2. Usuários" }), nodeBase(id(`scope:${profile}`, "modules"), "module", "Gestão de Permissões", "Módulos liberados", base, { isScopeHub: true, scopeType: "modules", profileType: profile, layer: 2, layerLabel: "2. Permissões", count: catalog(profile).length }), nodeBase(id(`scope:${profile}`, "requests"), "module", "Solicitações", "Solicitações", base.filter((x) => x.type === "access_request"), { isScopeHub: true, scopeType: "requests", profileType: profile, layer: 2, layerLabel: "2. Solicitações" }), nodeBase(id(`scope:${profile}`, "agenda"), "module", "Agenda", "Agenda", base.filter((x) => modLabel(x.module) === "Agenda" || x.type === "event"), { isScopeHub: true, scopeType: "agenda", profileType: profile, layer: 2, layerLabel: "2. Agenda" })];
  const visibleScopes = leader(profile) ? scopes : scopes.filter((s) => s.label !== "Solicitações");
  graphNodes.push(...visibleScopes);
  visibleScopes.forEach((s) => graphEdges.push({ id: `${profileNode.id}-${s.id}`, source: profileNode.id, target: s.id, label: s.label === "Módulos liberados" ? "permissões" : "abre", type: s.label === "Módulos liberados" ? "permission_allows" : "relation", status: s.status }));
  const userTypes = USER_TYPES.map((t) => nodeBase(id("user-type", t), "profile", "Usuários", t, base.filter((x) => n(userType(x)) === n(t)), { isUserTypeHub: true, userType: t, layer: 3, layerLabel: "3. Tipo de usuário" }));
  graphNodes.push(...userTypes);
  userTypes.forEach((u) => graphEdges.push({ id: `${visibleScopes[1]?.id}-${u.id}`, source: visibleScopes[1]?.id ?? profileNode.id, target: u.id, label: "tipo", type: "relation", status: u.status }));
  const users = Array.from(groupUsers(base).entries()).slice(0, 18).map(([key, items]) => ({ id: id(`user:${company?.id ?? "all"}`, key), type: "person" as const, module: "Usuários", label: userName(items[0]), status: status(items), size: "md" as const, companyId: company?.id, companyName: company?.name, information: `${userName(items[0])}: ${items.length} item(ns).`, metadata: { isUserHub: true, userKey: key, userType: userType(items[0]), layer: 3, layerLabel: "3. Usuário", count: items.length, pendingCount: pend(items), companyColor: color(company?.id ?? null) } }));
  if (leader(profile) || companyProfile(profile) || selectedNode?.metadata?.scopeType === "users") { graphNodes.push(...users); users.forEach((u) => { const parent = userTypes.find((t) => n(t.metadata?.userType) === n(u.metadata?.userType)); graphEdges.push({ id: `${parent?.id ?? visibleScopes[1]?.id}-${u.id}`, source: parent?.id ?? visibleScopes[1]?.id ?? profileNode.id, target: u.id, label: "usuário", type: "created_by", status: u.status }); }); }
  const companiesToShow = selectedCompanyId ? companies.filter((c) => c.id === selectedCompanyId) : companies;
  const companyNodes = companiesToShow.map((c) => ({ id: `company:${c.id}`, type: "company" as const, module: "Empresas", label: c.name, status: status(base), size: "lg" as const, companyId: c.id, companyName: c.name, information: `${c.name} no contexto do perfil ${profile}.`, metadata: { isCompanyHub: true, layer: 3, layerLabel: "3. Empresa", companyColor: color(c.id), count: base.filter((x) => companyKey(x) === c.id).length } }));
  graphNodes.push(...companyNodes);
  companyNodes.forEach((c) => graphEdges.push({ id: `${visibleScopes[0]?.id}-${c.id}`, source: visibleScopes[0]?.id ?? profileNode.id, target: c.id, label: "empresa", type: "belongs_to_company", status: c.status, companyId: c.companyId, metadata: { companyColor: c.metadata?.companyColor } }));
  if (projects.length && selectedProjectId) { const p = projects.find((x) => x.id === selectedProjectId); if (p) { const pn = { id: `project:${p.id}`, type: "project" as const, module: "Projeto", label: p.name, status: status(base), size: "lg" as const, projectId: p.id, projectName: p.name, companyId: p.companyId ?? undefined, metadata: { isProjectHub: true, layer: 3, layerLabel: "3. Projeto" } }; graphNodes.push(pn); graphEdges.push({ id: `${companyNodes[0]?.id ?? profileNode.id}-${pn.id}`, source: companyNodes[0]?.id ?? profileNode.id, target: pn.id, label: "projeto", type: "belongs_to_project", status: pn.status }); } }
  const modules = catalog(profile);
  const moduleNodes = modules.map((m) => ({ id: id("module", m.label), type: "module" as const, module: m.label, label: m.label, status: status(base.filter((x) => modLabel(x.module) === m.label)), size: "lg" as const, information: `${m.label}: ${screens(profile, m.label).length} tela(s)/ação(ões) liberada(s).`, metadata: { isModuleHub: true, module: m.id, moduleLabel: m.label, layer: 4, layerLabel: "4. Módulo liberado", count: screens(profile, m.label).length, permissionScreens: screens(profile, m.label).map((r) => r.item.label), source: "permission-catalog" } }));
  graphNodes.push(...moduleNodes);
  moduleNodes.forEach((m) => graphEdges.push({ id: `${visibleScopes[2]?.id}-${m.id}`, source: visibleScopes[2]?.id ?? profileNode.id, target: m.id, label: "módulo liberado", type: "permission_allows", status: m.status }));
  const permissionNodes = (moduleFocus ? screens(profile, moduleFocus) : []).map((r) => screenNode(profile, r));
  const detail = (moduleFocus || hasActiveFilter ? base.filter((x) => !moduleFocus || modLabel(x.module) === modLabel(moduleFocus)).slice(0, hasActiveFilter ? 36 : 24) : []).map((x) => ({ ...x, metadata: { ...x.metadata, isDetailNode: true, layer: 6, layerLabel: "6. Item do sistema" } }));
  graphNodes.push(...permissionNodes, ...detail);
  const moduleTarget = moduleFocus ? moduleNodes.find((m) => n(m.label) === n(modLabel(moduleFocus)))?.id ?? visibleScopes[2]?.id ?? profileNode.id : visibleScopes[2]?.id ?? profileNode.id;
  permissionNodes.forEach((p) => graphEdges.push({ id: `${moduleTarget}-${p.id}`, source: moduleTarget, target: p.id, label: "tela liberada", type: "permission_allows", status: p.status, module: p.module }));
  detail.forEach((d) => graphEdges.push({ id: `${moduleTarget}-${d.id}`, source: moduleTarget, target: d.id, label: "item", type: "contains", status: d.status, companyId: d.companyId, projectId: d.projectId, module: d.module }));
  const kept = new Set(graphNodes.map((x) => x.id));
  const keptEdges = edges.filter((e) => kept.has(e.source) && kept.has(e.target)).map((e) => ({ ...e, metadata: { ...e.metadata, companyColor: color(e.companyId ?? null) } }));
  return { nodes: uniq(graphNodes), edges: uniq([...graphEdges, ...keptEdges]), focusNodeId: selectedNode?.id ?? profileNode.id, focusModule: modLabel(moduleFocus ?? selectedProfileType ?? "Quality Control") };
}
